# Setup

In [ ]:
%%bash
python ./generate_data.py
python ./run_ddl.py

In [ ]:
%%sql --show
use prod.db

# Chapter 1

In [34]:
%%sql
SELECT
  *
FROM
  customer
LIMIT
  1;

+-----------+--------------------+-------------------+-------------+-----------------+-----------+--------------+----------------------------------------------------------------+
| c_custkey |             c_name |         c_address | c_nationkey |         c_phone | c_acctbal | c_mktsegment |                                                      c_comment |
+-----------+--------------------+-------------------+-------------+-----------------+-----------+--------------+----------------------------------------------------------------+
|         1 | Customer#000000001 | j5JsirBM9PsCy0O1m |          15 | 25-989-741-2988 |    711.56 |     BUILDING | y final requests wake slyly quickly special accounts. blithely |
+-----------+--------------------+-------------------+-------------+-----------------+-----------+--------------+----------------------------------------------------------------+

In [35]:
%%sql
-- use * to specify all columns
SELECT
  *
FROM
  orders
LIMIT
  5;

+------------+-----------+---------------+--------------+-------------+-----------------+-----------------+----------------+---------------------------------------------------------------------------+
| o_orderkey | o_custkey | o_orderstatus | o_totalprice | o_orderdate | o_orderpriority |         o_clerk | o_shippriority |                                                                 o_comment |
+------------+-----------+---------------+--------------+-------------+-----------------+-----------------+----------------+---------------------------------------------------------------------------+
|          1 |      3691 |             O |    194029.55 |  1996-01-02 |           5-LOW | Clerk#000000951 |              0 |                                        ly express platelets. deposits acc |
|          2 |      7801 |             O |     60951.63 |  1996-12-01 |        1-URGENT | Clerk#000000880 |              0 |                  ve the furiously fluffy dependencies. carefully regular  |
|          3 |     12332 |             F |    247296.05 |  1993-10-14 |           5-LOW | Clerk#000000955 |              0 |  after the asymptotes. instructions cajole after the foxes. carefully unu |
|          4 |     13678 |             O |     53829.87 |  1995-10-11 |           5-LOW | Clerk#000000124 |              0 |    st the furiously bold pinto beans. furiously pending theodolites cajol |
|          5 |      4450 |             F |    139660.54 |  1994-07-30 |           5-LOW | Clerk#000000925 |              0 |                    onic requests. carefully daring foxes among the carefu |
+------------+-----------+---------------+--------------+-------------+-----------------+-----------------+----------------+---------------------------------------------------------------------------+

In [36]:
%%sql
-- use * to specify all columns
SELECT
  *
FROM
  orders
LIMIT
  5;

+------------+-----------+---------------+--------------+-------------+-----------------+-----------------+----------------+---------------------------------------------------------------------------+
| o_orderkey | o_custkey | o_orderstatus | o_totalprice | o_orderdate | o_orderpriority |         o_clerk | o_shippriority |                                                                 o_comment |
+------------+-----------+---------------+--------------+-------------+-----------------+-----------------+----------------+---------------------------------------------------------------------------+
|          1 |      3691 |             O |    194029.55 |  1996-01-02 |           5-LOW | Clerk#000000951 |              0 |                                        ly express platelets. deposits acc |
|          2 |      7801 |             O |     60951.63 |  1996-12-01 |        1-URGENT | Clerk#000000880 |              0 |                  ve the furiously fluffy dependencies. carefully regular  |
|          3 |     12332 |             F |    247296.05 |  1993-10-14 |           5-LOW | Clerk#000000955 |              0 |  after the asymptotes. instructions cajole after the foxes. carefully unu |
|          4 |     13678 |             O |     53829.87 |  1995-10-11 |           5-LOW | Clerk#000000124 |              0 |    st the furiously bold pinto beans. furiously pending theodolites cajol |
|          5 |      4450 |             F |    139660.54 |  1994-07-30 |           5-LOW | Clerk#000000925 |              0 |                    onic requests. carefully daring foxes among the carefu |
+------------+-----------+---------------+--------------+-------------+-----------------+-----------------+----------------+---------------------------------------------------------------------------+

In [37]:
%%sql
-- use column c_names only to read data from those columns
SELECT
  o_orderkey,
  o_totalprice
FROM
  orders
LIMIT
  5;

+------------+--------------+
| o_orderkey | o_totalprice |
+------------+--------------+
|          1 |    194029.55 |
|          2 |     60951.63 |
|          3 |    247296.05 |
|          4 |     53829.87 |
|          5 |    139660.54 |
+------------+--------------+

In [38]:
%%sql
-- all customer rows that have c_nationkey = 20
SELECT
  *
FROM
  customer
WHERE
  c_nationkey = 20
LIMIT
  10;

+-----------+--------------------+------------------------------------------+-------------+-----------------+-----------+--------------+--------------------------------------------------------------------------------------------------------------------+
| c_custkey |             c_name |                                c_address | c_nationkey |         c_phone | c_acctbal | c_mktsegment |                                                                                                          c_comment |
+-----------+--------------------+------------------------------------------+-------------+-----------------+-----------+--------------+--------------------------------------------------------------------------------------------------------------------+
|         6 | Customer#000000006 |      g1s,pzDenUEBW3O,2 pxu0f9n2g64rJrt5E |          20 | 30-114-968-4951 |   7638.57 |   AUTOMOBILE |            quickly silent asymptotes are slyly regular excuses. instructions wake furiously? quickly bold courts p |
|        81 | Customer#000000081 |                       9jUFbrThIIeoUNd8 9 |          20 | 30-165-277-3269 |   2023.71 |     BUILDING |                                 s against the ironic packages haggle carefully above the slyly express pinto beans |
|       100 | Customer#000000100 |                           MBy6qq3OEGpV4u |          20 | 30-749-445-4907 |   9889.89 |    FURNITURE |                                     dazzle carefully furiously final foxes. express, ironic packages among the qui |
|       210 | Customer#000000210 |                   ,XOlfSzkZDAkm96adR41j, |          20 | 30-876-248-9750 |   7250.14 |    HOUSEHOLD |                                                                              es cajole bravely across the blithely |
|       223 | Customer#000000223 |                    MyQxUcG0P QCetmG00GlF |          20 | 30-193-643-1517 |   7476.20 |     BUILDING |           xcuses. silent theodolites across the carefully bold excuses sleep ironic, final courts. regular excuses |
|       228 | Customer#000000228 | rZ1wxvHNByT71bUJWZjXMDROzlAch6FVu,dj8Zfq |          20 | 30-435-915-1603 |   6868.12 |    FURNITURE |                                                                                      es. blithely permanent sentim |
|       247 | Customer#000000247 |                       eSAW4XaakYFj2WToKU |          20 | 30-151-905-3513 |   8495.92 |    HOUSEHOLD |                               tes nag according to the blithe, even packages. sometimes unusual packages integrate |
|       278 | Customer#000000278 |                         XHAfHlrYQM3elmhJ |          20 | 30-445-570-5841 |   7621.56 |     BUILDING | ely unusual accounts. stealthily special instructions affix blithely. regular, ironic packages sleep even platelet |
|       285 | Customer#000000285 |      rB6fTQKle64k3MvCCatad8DfMgR5OZA G4r |          20 | 30-235-130-1313 |   7276.72 |    FURNITURE |                slyly according to the blithely special instructions. ironic ideas against the blithely furious pac |
|       321 | Customer#000000321 |          LX0SKs3jqo9wH1yixIdGWp2ItclDiuL |          20 | 30-114-675-9153 |   7718.77 |    FURNITURE |                               ng the final, bold requests. furiously regular accounts inside the furiously pending |
+-----------+--------------------+------------------------------------------+-------------+-----------------+-----------+--------------+--------------------------------------------------------------------------------------------------------------------+

In [39]:
%%sql
-- all customer rows that have c_nationkey = 20 and c_acctbal > 1000
SELECT
  *
FROM
  customer
WHERE
  c_nationkey = 20
  AND c_acctbal > 1000
LIMIT
  10;

+-----------+--------------------+------------------------------------------+-------------+-----------------+-----------+--------------+--------------------------------------------------------------------------------------------------------------------+
| c_custkey |             c_name |                                c_address | c_nationkey |         c_phone | c_acctbal | c_mktsegment |                                                                                                          c_comment |
+-----------+--------------------+------------------------------------------+-------------+-----------------+-----------+--------------+--------------------------------------------------------------------------------------------------------------------+
|         6 | Customer#000000006 |      g1s,pzDenUEBW3O,2 pxu0f9n2g64rJrt5E |          20 | 30-114-968-4951 |   7638.57 |   AUTOMOBILE |            quickly silent asymptotes are slyly regular excuses. instructions wake furiously? quickly bold courts p |
|        81 | Customer#000000081 |                       9jUFbrThIIeoUNd8 9 |          20 | 30-165-277-3269 |   2023.71 |     BUILDING |                                 s against the ironic packages haggle carefully above the slyly express pinto beans |
|       100 | Customer#000000100 |                           MBy6qq3OEGpV4u |          20 | 30-749-445-4907 |   9889.89 |    FURNITURE |                                     dazzle carefully furiously final foxes. express, ironic packages among the qui |
|       210 | Customer#000000210 |                   ,XOlfSzkZDAkm96adR41j, |          20 | 30-876-248-9750 |   7250.14 |    HOUSEHOLD |                                                                              es cajole bravely across the blithely |
|       223 | Customer#000000223 |                    MyQxUcG0P QCetmG00GlF |          20 | 30-193-643-1517 |   7476.20 |     BUILDING |           xcuses. silent theodolites across the carefully bold excuses sleep ironic, final courts. regular excuses |
|       228 | Customer#000000228 | rZ1wxvHNByT71bUJWZjXMDROzlAch6FVu,dj8Zfq |          20 | 30-435-915-1603 |   6868.12 |    FURNITURE |                                                                                      es. blithely permanent sentim |
|       247 | Customer#000000247 |                       eSAW4XaakYFj2WToKU |          20 | 30-151-905-3513 |   8495.92 |    HOUSEHOLD |                               tes nag according to the blithe, even packages. sometimes unusual packages integrate |
|       278 | Customer#000000278 |                         XHAfHlrYQM3elmhJ |          20 | 30-445-570-5841 |   7621.56 |     BUILDING | ely unusual accounts. stealthily special instructions affix blithely. regular, ironic packages sleep even platelet |
|       285 | Customer#000000285 |      rB6fTQKle64k3MvCCatad8DfMgR5OZA G4r |          20 | 30-235-130-1313 |   7276.72 |    FURNITURE |                slyly according to the blithely special instructions. ironic ideas against the blithely furious pac |
|       321 | Customer#000000321 |          LX0SKs3jqo9wH1yixIdGWp2ItclDiuL |          20 | 30-114-675-9153 |   7718.77 |    FURNITURE |                               ng the final, bold requests. furiously regular accounts inside the furiously pending |
+-----------+--------------------+------------------------------------------+-------------+-----------------+-----------+--------------+--------------------------------------------------------------------------------------------------------------------+

In [40]:
%%sql
-- all customer rows that have c_nationkey = 20 or c_acctbal > 1000
SELECT
  *
FROM
  customer
WHERE
  c_nationkey = 20
  OR c_acctbal > 1000
LIMIT
  10;

+-----------+--------------------+---------------------------------------+-------------+-----------------+-----------+--------------+-------------------------------------------------------------------------------------------------------------------+
| c_custkey |             c_name |                             c_address | c_nationkey |         c_phone | c_acctbal | c_mktsegment |                                                                                                         c_comment |
+-----------+--------------------+---------------------------------------+-------------+-----------------+-----------+--------------+-------------------------------------------------------------------------------------------------------------------+
|         3 | Customer#000000003 |                          fkRGN8nY4pkE |           1 | 11-719-748-3364 |   7498.12 |   AUTOMOBILE |            fully. carefully silent instructions sleep alongside of the slyly regular asymptotes. quickly regular  |
|         4 | Customer#000000004 |                           4u58h fqkyE |           4 | 14-128-190-5944 |   2866.83 |    MACHINERY |                                                                  sublate. fluffily even instructions are about th |
|         6 | Customer#000000006 |   g1s,pzDenUEBW3O,2 pxu0f9n2g64rJrt5E |          20 | 30-114-968-4951 |   7638.57 |   AUTOMOBILE |           quickly silent asymptotes are slyly regular excuses. instructions wake furiously? quickly bold courts p |
|         7 | Customer#000000007 |        8OkMVLQ1dK6Mbu6WG9 w4pLGQ n7MQ |          18 | 28-190-982-9759 |   9561.95 |   AUTOMOBILE |                                    ounts. ironic, regular accounts sleep. final requests haggle quickly after the |
|         8 | Customer#000000008 | j,pZ,Qp,qtFEo0r0c 92qobZtlhSuOqbE4JGV |          17 | 27-147-574-9335 |   6819.74 |     BUILDING | riously final excuses sublate quickly among the fluffily even foxes. quickly final packages haggle furiously furi |
|         9 | Customer#000000009 |            vgIql8H6zoyuLMFNdAMLyE7 H9 |           8 | 18-338-906-3675 |   8324.07 |    FURNITURE |                     ss pinto beans believe slyly quiet deposits-- doggedly bold packages boost. quickly ironic de |
|        10 | Customer#000000010 |    Vf mQ6Ug9Ucf5OKGYq fsaX AtfsO7,rwY |           5 | 15-741-346-9870 |   2753.54 |    HOUSEHOLD |                                                                                   g quickly after the evenly bold |
|        12 | Customer#000000012 |                         Sb4gxKs7W1AZa |          13 | 23-791-276-1263 |   3396.49 |    HOUSEHOLD |             ickly regular dependencies boost blithely around the slyly ironic theodolites. furiously special dolp |
|        13 | Customer#000000013 |               Ez3ax0D5HnUbeUVSxoX8a8B |           3 | 13-761-547-5974 |   3857.34 |     BUILDING |                quickly brave foxes. blithely even packages against the pinto beans boost furiously against the re |
|        14 | Customer#000000014 |                       h3GFMzeFfYiamqr |           1 | 11-845-129-3851 |   5266.30 |    FURNITURE |                                                                                 r, express foxes cajole slyly aga |
+-----------+--------------------+---------------------------------------+-------------+-----------------+-----------+--------------+-------------------------------------------------------------------------------------------------------------------+

In [41]:
%%sql
-- all customer rows that have (c_nationkey = 20 and c_acctbal > 1000) or rows that have c_nationkey = 11
SELECT
  *
FROM
  customer
WHERE
  (
    c_nationkey = 20
    AND c_acctbal > 1000
  )
  OR c_nationkey = 11
LIMIT
  10;

+-----------+--------------------+------------------------------------------+-------------+-----------------+-----------+--------------+----------------------------------------------------------------------------------------------------------+
| c_custkey |             c_name |                                c_address | c_nationkey |         c_phone | c_acctbal | c_mktsegment |                                                                                                c_comment |
+-----------+--------------------+------------------------------------------+-------------+-----------------+-----------+--------------+----------------------------------------------------------------------------------------------------------+
|         6 | Customer#000000006 |      g1s,pzDenUEBW3O,2 pxu0f9n2g64rJrt5E |          20 | 30-114-968-4951 |   7638.57 |   AUTOMOBILE |  quickly silent asymptotes are slyly regular excuses. instructions wake furiously? quickly bold courts p |
|        52 | Customer#000000052 |              UracAlAA8tSHL5V,poTZIOjh8o, |          11 | 21-186-284-5998 |   5630.28 |    HOUSEHOLD |                                ts boost. carefully express waters across the blithely regular foxes inte |
|        81 | Customer#000000081 |                       9jUFbrThIIeoUNd8 9 |          20 | 30-165-277-3269 |   2023.71 |     BUILDING |                       s against the ironic packages haggle carefully above the slyly express pinto beans |
|        84 | Customer#000000084 |      GB3sUmv RRXV DPzeOSbGxMIF9Z4Eq9 rop |          11 | 21-546-818-3802 |   5174.71 |    FURNITURE |                   ounts. blithely express theodolites nag carefully ironic pinto beans. carefully final  |
|       100 | Customer#000000100 |                           MBy6qq3OEGpV4u |          20 | 30-749-445-4907 |   9889.89 |    FURNITURE |                           dazzle carefully furiously final foxes. express, ironic packages among the qui |
|       131 | Customer#000000131 |            ItdUFrHPZlzjZ, fo03sG4topAKTV |          11 | 21-840-210-3572 |   8595.53 |    HOUSEHOLD |                            ly final Tiresias. slyly permanent theodolites cajole quickly. carefully unus |
|       134 | Customer#000000134 |               6I1TTaoG7bbiogCqRcptG6BYme |          11 | 21-200-159-5932 |   4608.90 |     BUILDING |                                                                    ly regular dolphins haggle blithely.  |
|       148 | Customer#000000148 |                   qJ8bFn4kwiit7RzwGrwo5m |          11 | 21-562-498-6636 |   2135.60 |    HOUSEHOLD |  e carefully pending ideas detect slyly along the furiously special excuses. instructions use carefully  |
|       190 | Customer#000000190 | mY30kK8AfsTGrx,L4zI   QlQnnmCUxikyc8QcZ7 |          11 | 21-730-373-8193 |   1657.46 |   AUTOMOBILE |                                                               y even packages engage furiously pending p |
|       210 | Customer#000000210 |                   ,XOlfSzkZDAkm96adR41j, |          20 | 30-876-248-9750 |   7250.14 |    HOUSEHOLD |                                                                    es cajole bravely across the blithely |
+-----------+--------------------+------------------------------------------+-------------+-----------------+-----------+--------------+----------------------------------------------------------------------------------------------------------+

In [42]:
%%sql
-- all customer rows where the c_name has a 381 in it
SELECT
  *
FROM
  customer
WHERE
  c_name LIKE '%381%';

+-----------+--------------------+------------------------------------------+-------------+-----------------+-----------+--------------+---------------------------------------------------------------------------------------------------------------------+
| c_custkey |             c_name |                                c_address | c_nationkey |         c_phone | c_acctbal | c_mktsegment |                                                                                                           c_comment |
+-----------+--------------------+------------------------------------------+-------------+-----------------+-----------+--------------+---------------------------------------------------------------------------------------------------------------------+
|       381 | Customer#000000381 |                         wXs5zN2nPHqPsfFO |           5 | 15-860-208-7093 |   9931.71 |     BUILDING |                                                     ithely along the regular, regular theodolites. fluffily pending |
|      1381 | Customer#000001381 |    kAgLl7nUiPStCleWOiKevH3QAOhqtg9dVvrdN |          22 | 32-418-900-6494 |    367.82 |     BUILDING |                                                                           posits sleep carefully around the slyly e |
|      2381 | Customer#000002381 |  z7B43DZ7RGlkgEi3YaXfy,Aw2SZepYurvII41Do |           5 | 15-493-990-8133 |    412.99 |    FURNITURE |                                                          ul requests use slyly quickly even deposits. slyly pending |
|      3381 | Customer#000003381 |                    03jULkpVTm92eKW24meIj |          13 | 23-441-750-5088 |   2473.54 |   AUTOMOBILE |                                                  er the carefully bold multipliers doze blithely along the furiousl |
|      3810 | Customer#000003810 |                       hlRTIO4e4HNahc8A D |          18 | 28-881-994-8196 |   9906.80 |    FURNITURE |                                                                                    bold requests after the furiousl |
|      3811 | Customer#000003811 |                      b6vEJqifAgSbGhzTwTz |          22 | 32-962-997-2221 |   5697.04 |    FURNITURE |                                                   he carefully special packages. regular deposits sleep blithely bl |
|      3812 | Customer#000003812 |                               HGYp5dZtlA |          14 | 24-653-654-5032 |   4204.53 |    FURNITURE |                                                                                  y ironic requests believe blithely |
|      3813 | Customer#000003813 |            Aeky0En0JO5V1zRgFZ9EvCcBWaTmW |           6 | 16-983-191-7833 |   -494.03 |    HOUSEHOLD |                                                                     rding to the express foxes. bold platelets main |
|      3814 | Customer#000003814 |             FQ3lWCA3znooc3S SmDCfwqdn4R9 |          20 | 30-833-732-5401 |   -207.83 |   AUTOMOBILE |                                                                              ounts alongside of the fluffily pendin |
|      3815 | Customer#000003815 |                   S5SIUeDCuVOKRTZqZ5M4CC |          19 | 29-968-870-7672 |   2887.99 |    FURNITURE |                                                                         ccounts. fluffily bold requests sleep furio |
|      3816 | Customer#000003816 |                               kFLu9DYSXH |           6 | 16-806-750-3968 |   4353.05 |   AUTOMOBILE |                                g the carefully ironic asymptotes. furiously ironic foxes haggle. fluffily bold pack |
|      3817 | Customer#000003817 |    IWp4rgxgRxvUeHK2xtX8SEfGYmHYrCCpbBwXm |          16 | 26-142-669-5787 |   9766.42 |   AUTOMOBILE |                                            es until the bold instructions wake quickly carefully unusual packages;  |
|      3818 | Customer#000003818 | yrvC8HiUJVCsu7MyFHcyTcmAP0NgEWnoXQgTAz36 |           7 | 17-983-218-3716 |    346.99 |   AUTOMOBILE |                            theodolites. special instructions are blithely slyly special pinto beans; unusual, bold  |
|      3819 | Customer#000003819 |                            TejxSl9G1aF1x |           4 | 14-964-709-5782 |   -210.31 |     BUILDING |     os. excuses boost quickly across the carefully bold deposits. permanently pending accounts cajole. silent, clos |
|      4381 | Customer#000004381 |              MIQXH5W6Zsup5cVYfCtWupiJtgi |           2 | 12-570-797-1472 |   2542.55 |    HOUSEHOLD |                                                                          r deposits. carefully even packages along  |
|      5381 | Customer#000005381 |           bXQ,KuigJB1nASXN73PDwNOvXCIkp5 |           5 | 15-700-184-7619 |   4130.88 |    MACHINERY |                                                               es. carefully ironic ideas sleep blithely about the i |
|      6381 | Customer#000006381 |                    BKfk07DtN45gg2w4mMUK1 |           7 | 17-877-502-9214 |   7346.88 |    HOUSEHOLD |               inal asymptotes boost. bold, ironic requests are along the regular, special packages. pending account |
|      7381 | Customer#000007381 |       yq7RXRmclCUi6wJspelKaEWSJ  TfycLah |          20 | 30-666-139-1602 |     73.39 |     BUILDING | fluffily special requests are about the fluffily unusual foxes. final frets are slyly fluffily final deposits. even |
|      8381 | Customer#000008381 |    7kbg8wegbgGmgiW8OQ4SbJ8colXl6rpBmHudJ |           0 | 10-177-308-9094 |   6674.59 |   AUTOMOBILE |           uests against the carefully bold excuses sleep blithely slyly final instructions; unusual requests about  |
|      9381 | Customer#000009381 |                            BhXODcEOpwNg6 |          17 | 27-708-588-6706 |   4788.15 |    HOUSEHOLD |                      sual hockey players use above the final packages. quickly ironic excuses sleep. slyly final pa |
|     10381 | Customer#000010381 |                             RLDSr5JOMK45 |          15 | 25-294-314-6077 |    106.15 |    FURNITURE |                                                       r the furiously unusual pinto beans. blithely ironic pinto be |
|     11381 | Customer#000011381 |                         cHcQKKDGnWLbq48O |           7 | 17-652-294-7849 |   1959.81 |    MACHINERY |                                                                    structions. slyly ironic requests play furiously |
|     12381 | Customer#000012381 |          hPUYchVeqkeLC1QCsGJXF5Fj6QDQhkd |          13 | 23-989-969-2819 |   1172.56 |    HOUSEHOLD |                                                          cies cajole carefully. unusual, ironic ideas believe caref |
|     13381 | Customer#000013381 |                          TkAwDfheF4H3g9H |           9 | 19-465-107-1496 |   3221.83 |    HOUSEHOLD |                            efully regular foxes. ironic platelets sleep above the regular deposits. furiously slow  |
|     13810 | Customer#000013810 |            KDptBRwrSNgIfqVU,Si2smGKFLFix |          18 | 28-953-486-1222 |   5133.48 |     BUILDING |                                                   lithely. slyly ironic pinto beans nag. ironic, regular packages a |
|     13811 | Customer#000013811 |              XvajiqJbFBaY8IfkIPanJeDnrba |          19 | 29-964-589-6640 |   3436.54 |    MACHINERY |                                                           ly regular theodolites: courts nag blithely. bold request |
|     13812 | Customer#000013812 | WuM0MP,N22TPjuHnUzDbcyJF86fkycoa8L7xPsKK |           0 | 10-571-845-2630 |   5982.87 |   AUTOMOBILE |                                                        lar ideas use carefully alongside of the fluffily final plat |
|     13813 | Customer#000013813 |                          Xh5saiXGJkv5 lL |          21 | 31-140-142-6191 |   1190.11 |    MACHINERY |                      te blithely even instructions. regular, final orbits nag carefully. carefully bold dinos wake  |
|     13814 | Customer#000013814 |                 PnsbC4EN7J4TZ30 yPPlI8xh |          17 | 27-767-457-2550 |   2131.39 |    FURNITURE |                                                            instructions according to the furious, ironic platelets  |
|     13815 | Customer#000013815 |                       UHXyxzMMNwV dIRAGo |          11 | 21-606-813-1389 |   4240.37 |    FURNITURE |                                                   special deposits. carefully daring requests sleep blithely. caref |
|     13816 | Customer#000013816 |                  XX Nlht,5lD6vroOC75qAS  |          17 | 27-501-367-6604 |   7844.29 |   AUTOMOBILE |                                                          ully final excuses. carefully unusual accounts about the w |
|     13817 | Customer#000013817 |           eg1g5BqcUMPqvGy9oY7bjVe7nj6NsH |           3 | 13-978-449-6295 |   2094.32 |    FURNITURE |                                                    slyly. even theodolites nag regularly-- furiously even foxes abo |
|     13818 | Customer#000013818 |              r17Nf8Y8iLfBKIGP6zJUrWl5K3g |          15 | 25-948-173-6359 |   8239.56 |    HOUSEHOLD |                                                                cial courts. excuses sleep quickly regular accounts. |
|     13819 | Customer#000013819 | 9MlFsiIsVNrVT8jJKRp30wISV5sNdXAwIT85F8S  |          12 | 22-868-584-6588 |   1312.29 |     BUILDING |                                                                              ackages. carefully special pinto beans |
|     14381 | Customer#000014381 |                            jakuN8Gt0SJNE |          21 | 31-449-680-6297 |   1915.30 |    FURNITURE |                         the even accounts cajole blithely furiously express theodolites. slyly regular platelets ha |
+-----------+--------------------+------------------------------------------+-------------+-----------------+-----------+--------------+---------------------------------------------------------------------------------------------------------------------+

In [43]:
%%sql
-- all customer rows where the c_name ends with a 381
SELECT
  *
FROM
  customer
WHERE
  c_name LIKE '%381';

+-----------+--------------------+-----------------------------------------+-------------+-----------------+-----------+--------------+---------------------------------------------------------------------------------------------------------------------+
| c_custkey |             c_name |                               c_address | c_nationkey |         c_phone | c_acctbal | c_mktsegment |                                                                                                           c_comment |
+-----------+--------------------+-----------------------------------------+-------------+-----------------+-----------+--------------+---------------------------------------------------------------------------------------------------------------------+
|       381 | Customer#000000381 |                        wXs5zN2nPHqPsfFO |           5 | 15-860-208-7093 |   9931.71 |     BUILDING |                                                     ithely along the regular, regular theodolites. fluffily pending |
|      1381 | Customer#000001381 |   kAgLl7nUiPStCleWOiKevH3QAOhqtg9dVvrdN |          22 | 32-418-900-6494 |    367.82 |     BUILDING |                                                                           posits sleep carefully around the slyly e |
|      2381 | Customer#000002381 | z7B43DZ7RGlkgEi3YaXfy,Aw2SZepYurvII41Do |           5 | 15-493-990-8133 |    412.99 |    FURNITURE |                                                          ul requests use slyly quickly even deposits. slyly pending |
|      3381 | Customer#000003381 |                   03jULkpVTm92eKW24meIj |          13 | 23-441-750-5088 |   2473.54 |   AUTOMOBILE |                                                  er the carefully bold multipliers doze blithely along the furiousl |
|      4381 | Customer#000004381 |             MIQXH5W6Zsup5cVYfCtWupiJtgi |           2 | 12-570-797-1472 |   2542.55 |    HOUSEHOLD |                                                                          r deposits. carefully even packages along  |
|      5381 | Customer#000005381 |          bXQ,KuigJB1nASXN73PDwNOvXCIkp5 |           5 | 15-700-184-7619 |   4130.88 |    MACHINERY |                                                               es. carefully ironic ideas sleep blithely about the i |
|      6381 | Customer#000006381 |                   BKfk07DtN45gg2w4mMUK1 |           7 | 17-877-502-9214 |   7346.88 |    HOUSEHOLD |               inal asymptotes boost. bold, ironic requests are along the regular, special packages. pending account |
|      7381 | Customer#000007381 |      yq7RXRmclCUi6wJspelKaEWSJ  TfycLah |          20 | 30-666-139-1602 |     73.39 |     BUILDING | fluffily special requests are about the fluffily unusual foxes. final frets are slyly fluffily final deposits. even |
|      8381 | Customer#000008381 |   7kbg8wegbgGmgiW8OQ4SbJ8colXl6rpBmHudJ |           0 | 10-177-308-9094 |   6674.59 |   AUTOMOBILE |           uests against the carefully bold excuses sleep blithely slyly final instructions; unusual requests about  |
|      9381 | Customer#000009381 |                           BhXODcEOpwNg6 |          17 | 27-708-588-6706 |   4788.15 |    HOUSEHOLD |                      sual hockey players use above the final packages. quickly ironic excuses sleep. slyly final pa |
|     10381 | Customer#000010381 |                            RLDSr5JOMK45 |          15 | 25-294-314-6077 |    106.15 |    FURNITURE |                                                       r the furiously unusual pinto beans. blithely ironic pinto be |
|     11381 | Customer#000011381 |                        cHcQKKDGnWLbq48O |           7 | 17-652-294-7849 |   1959.81 |    MACHINERY |                                                                    structions. slyly ironic requests play furiously |
|     12381 | Customer#000012381 |         hPUYchVeqkeLC1QCsGJXF5Fj6QDQhkd |          13 | 23-989-969-2819 |   1172.56 |    HOUSEHOLD |                                                          cies cajole carefully. unusual, ironic ideas believe caref |
|     13381 | Customer#000013381 |                         TkAwDfheF4H3g9H |           9 | 19-465-107-1496 |   3221.83 |    HOUSEHOLD |                            efully regular foxes. ironic platelets sleep above the regular deposits. furiously slow  |
|     14381 | Customer#000014381 |                           jakuN8Gt0SJNE |          21 | 31-449-680-6297 |   1915.30 |    FURNITURE |                         the even accounts cajole blithely furiously express theodolites. slyly regular platelets ha |
+-----------+--------------------+-----------------------------------------+-------------+-----------------+-----------+--------------+---------------------------------------------------------------------------------------------------------------------+

In [44]:
%%sql
-- all customer rows where the c_name starts with a 381
SELECT
  *
FROM
  customer
WHERE
  c_name LIKE '381%';

+-----------+--------+-----------+-------------+---------+-----------+--------------+-----------+
| c_custkey | c_name | c_address | c_nationkey | c_phone | c_acctbal | c_mktsegment | c_comment |
+-----------+--------+-----------+-------------+---------+-----------+--------------+-----------+
+-----------+--------+-----------+-------------+---------+-----------+--------------+-----------+

In [45]:
%%sql
-- all customer rows where the c_name has a combination of any character and 9 and 1
SELECT
  *
FROM
  customer
WHERE
  c_name LIKE '%_91%';

+-----------+--------------------+-----------------------------------------+-------------+-----------------+-----------+--------------+----------------------------------------------------------------------------------------------------------------------+
| c_custkey |             c_name |                               c_address | c_nationkey |         c_phone | c_acctbal | c_mktsegment |                                                                                                            c_comment |
+-----------+--------------------+-----------------------------------------+-------------+-----------------+-----------+--------------+----------------------------------------------------------------------------------------------------------------------+
|        91 | Customer#000000091 |   9Sce2m BjvDdjQkqMx8UnrUsJkk1IBAvZPTsA |           8 | 18-239-400-3677 |   4643.14 |   AUTOMOBILE |                              yly ironic foxes lose slyly pending asymptotes. slyly final theodolites nag blithely ar |
|       191 | Customer#000000191 |                       cZMo3 b4GwZtUmdbw |          16 | 26-811-707-6869 |   2945.16 |     BUILDING |                                                                                  daringly quickly ironic foxes. care |
|       291 | Customer#000000291 |                        2FfdPluDa2fxPaRh |           8 | 18-657-656-2318 |   4261.68 |    HOUSEHOLD |   ld deposits. regularly ironic pinto beans cajole permanently furiously express packages. regular, unusual sheaves  |
|       391 | Customer#000000391 |                     BZ,850WgpZ0YSFs79Sb |          11 | 21-604-451-4462 |   4801.30 |    HOUSEHOLD |                             tions wake about the blithely final instructions. excuses sleep regular requests. slyly  |
|       491 | Customer#000000491 |              AXsbcyMDujG,CAiEu4FmufbZ1k |           0 | 10-856-259-7548 |    785.37 |   AUTOMOBILE |                                                               ly final, even hockey players. carefully final ideas w |
|       591 | Customer#000000591 |                       wkmTqEmyI3UOEoG3q |          20 | 30-584-309-7885 |   6344.66 |    MACHINERY |             xpress deposits. slyly ironic ideas haggle: daringly even requests after the quickly final ideas boost q |
|       691 | Customer#000000691 |                  0aGn3Vcf6ZKi82ogENfnso |          16 | 26-741-688-4189 |   9566.15 |    MACHINERY |                         ven packages cajole fluffily fluffily unusual frays. ironic excuses sleep furiously. regular |
|       791 | Customer#000000791 |                     Y14aVvMuDDgnmEuCEPK |          13 | 23-575-775-4059 |   3694.81 |    HOUSEHOLD |                                                               beans use carefully furiously regular deposits. slyly  |
|       891 | Customer#000000891 |                       r4,EU38BM0qdbjwqH |          11 | 21-439-958-7518 |   6032.18 |    FURNITURE |                                                                                ong the quickly quick patterns. slyly |
|       910 | Customer#000000910 |                           bKS7h8o7ZEiRj |           9 | 19-899-463-4292 |   5794.69 |     BUILDING |                                 silent deposits are. blithely final foxes cajole slyly according to the furiously re |
|       911 | Customer#000000911 |               68,LIR0Fhraw6LUTrFW6Ew05u |          13 | 23-121-746-7339 |   6364.60 |     BUILDING |          uches. blithely silent requests haggle quick, bold accounts. carefully bold pinto beans according to the no |
|       912 | Customer#000000912 |                        OaqZYembag,qVEwo |          14 | 24-348-437-3105 |   3861.36 |    FURNITURE |                                                                              s sleep slyly along the regular, even i |
|       913 | Customer#000000913 |                        RCJd97HzePqdmZqv |          14 | 24-500-946-3315 |   6935.16 |    FURNITURE |                                         symptotes. platelets are carefully carefully special foxes. carefully unusua |
|       914 | Customer#000000914 |                   sfm DilMcxoMeKw6sbgj9 |           5 | 15-915-758-7313 |   1230.79 |    MACHINERY |                                                           ons. unusual requests cajole blithely boldly regular packa |
|       915 | Customer#000000915 |                  FykMsCZp9sPLb5F1Z0kS5F |           0 | 10-452-398-2445 |   3776.53 |   AUTOMOBILE |                                                     he even, bold instructions. quickly final foxes wake thinly care |
|       916 | Customer#000000916 |                    S1CTDHEshFRWaWbnVEPv |          23 | 33-511-587-8754 |    130.59 |    MACHINERY | ajole packages. carefully final excuses detect carefully among the furiously final instructions. regular courts wake |
|       917 | Customer#000000917 |       h1r780DE8lF6aGidEsF3Kva80dOlXvtsV |           1 | 11-100-917-5264 |   3679.65 |    HOUSEHOLD |                           iously slyly express ideas. quickly final ideas above the carefully special requests grow  |
|       918 | Customer#000000918 |                           58ByGoNkaauhU |          19 | 29-992-318-6425 |   -155.06 |    MACHINERY |        y regular platelets. regular, unusual packages sleep evenly. slyly bold accounts affix carefully. bold, final |
|       919 | Customer#000000919 |                            PjkyzB5w39Jg |           9 | 19-537-180-2200 |   9774.97 |    MACHINERY |                                           furiously regular gifts. stealthily regular instructions use regular, idle |
|       991 | Customer#000000991 |                              OgZkswZKF7 |          21 | 31-977-971-6175 |   6533.53 |   AUTOMOBILE |                    y final packages. regular, even pinto beans wake. bold packages run furiously. furious, regular d |
|      1091 | Customer#000001091 |                XtMTviXK6RZ91oBw7ynIT4z0 |          17 | 27-336-955-4882 |   -710.53 |     BUILDING |                                                 onic accounts are quickly. ironic instructions wake blithely against |
|      1191 | Customer#000001191 |       hRhTNKi3npZGKxPzi5N9pU9b,Rl0ka4ID |          19 | 29-587-244-2901 |   9088.54 |   AUTOMOBILE |                                                                       ic accounts detect requests. final, special de |
|      1291 | Customer#000001291 |        OKXJGOjIiRtAGTFYYWYaZScffmt0Zw20 |           7 | 17-693-294-2656 |   8227.37 |     BUILDING |                                                s, ironic packages are fluffily around the furiously careful packages |
|      1391 | Customer#000001391 |     UeAdVulIH4V2xQTg56UIUaeHHJthYg81mQa |          23 | 33-558-545-3053 |   5510.28 |    FURNITURE |   regular, regular requests. ideas are regular dependencies. foxes among the closely close accounts affix around the |
|      1491 | Customer#000001491 |                           lH1ibXlwVFBny |           4 | 14-931-281-5631 |   3739.82 |    HOUSEHOLD |                      y bold hockey players. quickly bold accounts are slyly final, pending dependencies. carefully i |
|      1591 | Customer#000001591 |                          2fhd7jD4EIxRQZ |           9 | 19-142-875-7741 |   7470.70 |    FURNITURE |                                                              he quickly unusual requests. pending, ironic accounts c |
|      1691 | Customer#000001691 |             qwQH1lfhnAtwhL1hzx5HOvQIupc |          12 | 22-649-185-6921 |   3367.22 |   AUTOMOBILE |                ously special packages. fluffily ironic pearls about the bold, special deposits boost closely ironic  |
|      1791 | Customer#000001791 |  EmxoaiZ0vIi6ATG0WlmnUHUmH2b,aNt Ijz741 |           8 | 18-937-127-3890 |   3917.82 |    HOUSEHOLD |                  packages sleep according to the quickly ironic platelets. fluffily unusual platelets sleep quickly. |
|      1891 | Customer#000001891 |                     vNJjDAYc l6K18m3ZR, |           9 | 19-323-409-2180 |   3069.79 |    HOUSEHOLD |    lar accounts. fluffily final asymptotes sleep blithely final packages. regular theodolites cajole carefully. regu |
|      1910 | Customer#000001910 |                         gaRu,,M,wYBlxd  |           5 | 15-112-377-2843 |    475.44 |    FURNITURE |                                                                                      sual packages would are furious |
|      1911 | Customer#000001911 |                            mRGcuFcffluo |           1 | 11-369-744-8780 |   2601.29 |    HOUSEHOLD |                                          to the carefully final deposits. slyly unusual theodolites detect. regular  |
|      1912 | Customer#000001912 | ,qjthdVjnBDVqIOt8rSscRbRuUb6xC7Vvv 8fmP |          20 | 30-784-527-9935 |   3886.95 |    FURNITURE |                re fluffily special requests. theodolites among the boldly even packages dazzle against the ironic ex |
|      1913 | Customer#000001913 |                       Y2QT3tHsN0iQtd0Id |           8 | 18-831-659-1744 |   8031.55 |     BUILDING |                 g to the fluffily final accounts ought to lose unusual, ironic accounts. slyly final deposits will x |
|      1914 | Customer#000001914 |               iAoQfLYDacw NbZoijdaSP04G |           6 | 16-458-421-7729 |   3308.34 |    FURNITURE |                                              ackages nag. blithely regular multipliers are. deposits haggle closely  |
|      1915 | Customer#000001915 |           meyaPruBxVxX0,d6umhv7YWz5Z7Kl |          16 | 26-683-446-1665 |   7268.98 |   AUTOMOBILE |              efully according to the ruthless, ironic accounts. furiously ironic requests cajole. carefully enticing |
|      1916 | Customer#000001916 |                        IlkoNN3h5gtwT2ng |           5 | 15-662-459-4512 |   1768.76 |    HOUSEHOLD |                                                 final requests run carefully after the instructions. regular, final  |
|      1917 | Customer#000001917 |              L14UMCaEg0j8xFiSrayrj4tyD3 |           7 | 17-940-989-5599 |   3470.08 |   AUTOMOBILE |      thrash carefully. slyly bold packages sleep against the blithely special instructions. even requests cajole abo |
|      1918 | Customer#000001918 |    p9pMyTeP2pw7KyNccs30JB6w7Jc B,x6aHDA |           9 | 19-987-388-4413 |   8539.61 |    MACHINERY |                                                                             refully. blithely final deposits nag car |
|      1919 | Customer#000001919 |                             GDL9O9ta38j |          18 | 28-664-832-4585 |   6262.18 |    HOUSEHOLD |                                                                                       dencies cajole around the idea |
|      1991 | Customer#000001991 |    amsK9oO0Y9mWQtQ6XPXK2JiNezIRhUQSPR,C |           9 | 19-351-767-3188 |   3517.27 |    FURNITURE |                                        out the furiously dogged escapades. furiously final packages haggle pending e |
|      2091 | Customer#000002091 |                       cpAjOTaY0sBMO,ZpO |          16 | 26-354-387-4231 |   2601.61 |    FURNITURE |                         arefully express accounts. blithely unusual accounts are furiously through the slyly regular |
|      2191 | Customer#000002191 |                     sk1nfTCwrBZM8k2xlVd |           7 | 17-107-715-5454 |   2005.99 |    MACHINERY |                                                                                  bravely regular ideas affix blithel |
|      2291 | Customer#000002291 |               GqxVD9B tw58tQQv7RODWPF87 |           5 | 15-553-777-4519 |    -13.83 |   AUTOMOBILE |                                         ing to the blithely ironic requests. ruthlessly unusual ideas cajole across  |
|      2391 | Customer#000002391 |                             rFNT5y y05, |          24 | 34-538-909-7828 |   -993.93 |     BUILDING |                                                                                grate silent accounts. silent deposit |
|      2491 | Customer#000002491 |                4b,wCPrQI7x4rGlAy,hZkyj5 |           7 | 17-111-683-1091 |   9386.50 |   AUTOMOBILE |                     ts use blithely according to the furiously ironic foxes. carefully even packages alongside of th |
|      2591 | Customer#000002591 |                        8RLmynQmQ75Wm,c0 |          18 | 28-695-347-3960 |   3319.74 |    FURNITURE |                                                      ar accounts detect quickly blithely unusual accounts. blithely  |
|      2691 | Customer#000002691 |       A, tJbLStpXccsOpdt8Li6GJX t0T4Xyj |          21 | 31-383-871-8222 |   1070.53 |    FURNITURE |                                                                         platelets. carefully silent platelets are fu |
|      2791 | Customer#000002791 |        3aQZWTkzULLA2HpXk8sXSnRe,fJQDkNi |           6 | 16-732-903-5535 |   1382.12 |   AUTOMOBILE |                                                                               wake busily above the regular, express |
|      2891 | Customer#000002891 |                             XJ8SXrbwmOO |           7 | 17-282-306-5219 |   4894.47 |    FURNITURE |                                                                      ss foxes. deposits integrate. final instruction |
|      2910 | Customer#000002910 |       2ooeLaogzg3cTxqgu FRUG5gAtlc5 00p |           1 | 11-391-736-1612 |   8357.46 |    MACHINERY |                                                   e ruthlessly pending accounts. unusual accounts nag. finally even  |
|      2911 | Customer#000002911 |                            imbkK2N9LrtC |          19 | 29-365-497-7730 |   2805.23 |    FURNITURE |                                             ter the even packages haggle furiously special requests. carefully unusu |
|      2912 | Customer#000002912 |       A7SbUSVDSpUUWqymJwEfPRHguMfKOO9Sm |          18 | 28-465-202-9678 |   -552.68 |    HOUSEHOLD |                                                               ide of the slyly express packages. furiously regular i |
|      2913 | Customer#000002913 |         ZQyuVx3dgACYpkIiC4Jf9 FYY3UUPIP |          16 | 26-622-551-8642 |   4101.76 |    HOUSEHOLD |                                                                              ly dependencies. quickly regular dolphi |
|      2914 | Customer#000002914 |                        JuBWQZOgRRCi3Uzp |          19 | 29-736-466-9105 |   -690.62 |    FURNITURE |               ckages wake up the furiously regular instructions. blithely ironic accounts integrate carefully. pendi |
|      2915 | Customer#000002915 |      n15IgA F1JhiKiS6zE,piQ1Tpn2iE8LSE, |           0 | 10-870-588-4934 |   6748.74 |    FURNITURE |                                 cajole. quickly ironic excuses wake slyly alongside of the blithely pending deposits |
|      2916 | Customer#000002916 |                 sC7mIpa9Fbt6acD8XALggWg |          13 | 23-879-865-6812 |   3052.46 |     BUILDING |                  wake fluffily even foxes. excuses affix. carefully special requests snooze carefully. carefully sly |
|      2917 | Customer#000002917 |            bzCDV0m7F0mryJOyoXi2rdeKX4FD |          17 | 27-939-570-1941 |   7643.30 |    MACHINERY |              ges are quickly! thinly final theodolites wake blithely. quickly final accounts are furiously quickly b |
|      2918 | Customer#000002918 |            x57eK,YVBypNH7rTVA23ne8PtbSO |          24 | 34-471-745-3416 |    924.86 |    HOUSEHOLD |                          ly after the theodolites. quickly special multipliers nag along the fluffily final instruct |
|      2919 | Customer#000002919 | CThKdXAE1WYGIhJq2QPIarekcFW,njEYdm39 TH |          23 | 33-365-556-6915 |   -948.02 |     BUILDING |                                           regular accounts doze finally pending dependencies! furiously unusual foxe |
|      2991 | Customer#000002991 |                Y0wbQA3u4viEZLe ndjwdMCr |           8 | 18-907-651-5481 |   5549.26 |    FURNITURE |                                                      regular dolphins wake carefully deposits. regular, final theodo |
|      3091 | Customer#000003091 |                    6aKsMqm7 MyGe634P9Uo |           2 | 12-848-402-5035 |   2051.91 |   AUTOMOBILE |  s sleep above the blithely ironic platelets. regular dependencies cajole carefully along the unusual instructions.  |
|      3191 | Customer#000003191 |            WCZjsmPDy2C2admD0R7pVWuTqOR8 |          19 | 29-535-757-7584 |   4314.25 |    MACHINERY |                                                                                     the final tithes haggle quickly  |
|      3291 | Customer#000003291 |                       Pxe1cEVjemTlfg8nU |          23 | 33-156-325-5084 |   3390.85 |   AUTOMOBILE |            its. furiously special deposits cajole blithely. quickly even accounts about the unusual, even instructio |
|      3391 | Customer#000003391 |        Sz4TynbDQNCL2ax6pJqkyw0dReOy0iN9 |           3 | 13-592-494-2668 |   7742.35 |     BUILDING |                                                                                      althily regular requests behind |
|      3491 | Customer#000003491 |     OZruqHXa6KKFaAYZqukGYG,0ee0NkCxLqn2 |          10 | 20-575-983-1678 |   4748.41 |    HOUSEHOLD |                                   . theodolites boost blithely silent foxes. carefully ironic pinto beans nag. speci |
|      3591 | Customer#000003591 |                        rq8MAfUlo9HDGtnX |           2 | 12-340-575-5823 |   3555.85 |     BUILDING |                                                                                     dencies wake requests. blithely  |
|      3691 | Customer#000003691 |                    GQXQ1ZNNWZdXFo88bDP6 |          10 | 20-758-985-1035 |   7967.22 |    MACHINERY |                                                                          the deposits. even packages sleep fluffily. |
|      3791 | Customer#000003791 |      9ApGfY1GaefneFkxeTxsXUJP4L8O9Pzz2k |           3 | 13-391-929-8365 |   8490.96 |    FURNITURE |                                                         y. blithely ironic accounts cajole furiously. pending instru |
|      3891 | Customer#000003891 |       E07vRMZVEz0,U,ls9ik1LqHEQD Dfo7RF |           1 | 11-927-163-1261 |   7596.67 |    MACHINERY |                                                                        equests above the blithely special accounts p |
|      3910 | Customer#000003910 |                   1vCZWFV3OT7wy9E,Ax38e |          12 | 22-790-171-6270 |   -183.86 |    FURNITURE |                            sts nag slyly. carefully bold packages use thinly. blithely pending ideas haggle furiousl |
|      3911 | Customer#000003911 |    taLupgYbVqYG2qBZJAS0 thm6YAF33K,mBS0 |           5 | 15-659-498-3817 |   9712.07 |    MACHINERY |                                               beans. doggedly final accounts sleep daringly. quickly final gifts mai |
|      3912 | Customer#000003912 |    Ex2vR49kgh9wqpjh3KZRtp6RkKX8abQP7Pjg |          21 | 31-638-158-8616 |    -90.52 |    HOUSEHOLD |    nic Tiresias. fluffily ironic requests integrate slyly. slyly pending dolphins sleep above the pinto beans! packa |
|      3913 | Customer#000003913 |                     m4m40RLg,PCxcbhjKg6 |          20 | 30-696-323-1702 |   5572.00 |   AUTOMOBILE |                                                  the carefully regular frays. carefully final requests after the car |
|      3914 | Customer#000003914 |                         zyIMHcMcJNoJar2 |           2 | 12-575-753-3202 |   3547.25 |   AUTOMOBILE |                         thely special accounts breach about the close accounts. pinto beans are furiously across the |
|      3915 | Customer#000003915 |                         ZH4YXQa,ta5YRS8 |          23 | 33-825-949-4537 |   7636.45 |    MACHINERY |                                            deposits cajole. requests haggle stealthy requests. furiously regular pac |

In [46]:
%%sql
-- all customer rows which have c_nationkey = 10 or c_nationkey = 20
SELECT
  *
FROM
  customer
WHERE
  c_nationkey IN (10, 20);

+-----------+--------------------+------------------------------------------+-------------+-----------------+-----------+--------------+----------------------------------------------------------------------------------------------------------------------+
| c_custkey |             c_name |                                c_address | c_nationkey |         c_phone | c_acctbal | c_mktsegment |                                                                                                            c_comment |
+-----------+--------------------+------------------------------------------+-------------+-----------------+-----------+--------------+----------------------------------------------------------------------------------------------------------------------+
|         6 | Customer#000000006 |      g1s,pzDenUEBW3O,2 pxu0f9n2g64rJrt5E |          20 | 30-114-968-4951 |   7638.57 |   AUTOMOBILE |              quickly silent asymptotes are slyly regular excuses. instructions wake furiously? quickly bold courts p |
|        16 | Customer#000000016 |                      P2IQMff18ercaYrO,40 |          10 | 20-781-609-3107 |   4681.03 |    FURNITURE |                                                  ests cajole. pinto beans detect slyly. final packages cajole slyly  |
|        41 | Customer#000000041 |          jeREsFtCuMqEwdvTFqTkY2NzGRYDG1m |          10 | 20-917-711-4011 |    270.95 |    HOUSEHOLD |             uctions wake carefully pending deposits: pinto beans along the carefully final deposits sleep blithely a |
|        49 | Customer#000000049 |    PdKqM4TlA OLTjaeRmvH7QWDu80USfslgqutF |          10 | 20-908-631-4424 |   4573.94 |    FURNITURE |                                                     quests haggle! furiously unusual theodolites cajole carefully. t |
|        55 | Customer#000000055 |   ti9p9XgdmFsjsQI6XQrISDUMFAusnmKS SBoCE |          10 | 20-180-440-8525 |   4572.11 |    MACHINERY |       dolites. bold instructions wake fluffily regular ideas. regular theodolites are furiously carefully unusual ac |
|        56 | Customer#000000056 |                            qh212iaGWtoVp |          10 | 20-895-685-6920 |   6530.86 |    FURNITURE |                         quickly final dependencies. even dependencies are slyly regularly silent theodolites. slow a |
|        81 | Customer#000000081 |                       9jUFbrThIIeoUNd8 9 |          20 | 30-165-277-3269 |   2023.71 |     BUILDING |                                   s against the ironic packages haggle carefully above the slyly express pinto beans |
|       100 | Customer#000000100 |                           MBy6qq3OEGpV4u |          20 | 30-749-445-4907 |   9889.89 |    FURNITURE |                                       dazzle carefully furiously final foxes. express, ironic packages among the qui |
|       104 | Customer#000000104 |          SEOogsfT y09vI2z PcSTnI18U6rNTf |          10 | 20-966-284-8065 |   -588.38 |    FURNITURE |                                                                                     efully bold deposits. carefully  |
|       105 | Customer#000000105 |                 XI8hMXfr8bIKTGhIRS2sYs,p |          10 | 20-793-553-6417 |   9091.82 |    MACHINERY |                                                                 solve pending, final requests. regular, bold platele |
|       110 | Customer#000000110 |                          FtEbLLBJQ24d2yG |          10 | 20-893-536-2069 |   7462.99 |   AUTOMOBILE |      unts. fluffily express dolphins cajole furiously. fluffily special pinto beans about the furiously express asym |
|       158 | Customer#000000158 |              ZjQ2uJ,hZUZ,QCi,oNltA40 4dt |          10 | 20-383-680-1329 |   6160.95 |   AUTOMOBILE |                                                                               inal asymptotes. ironic accounts detec |
|       159 | Customer#000000159 |            hCyzNocUmjEtz5xSYYzUCH1Bk1wF7 |          10 | 20-888-668-2668 |   2060.06 |    HOUSEHOLD |           refully blithely final orbits. pending, final packages after the carefully ironic platelets nag carefully  |
|       166 | Customer#000000166 |      ,Vj4kzvCbTUmhLNSVjuyf8716NF5SddgDMY |          10 | 20-320-530-5920 |   2042.21 |    FURNITURE |            osits. regular, express deposits hang closely blithely regular platelets. unusual theodolites haggle fluf |
|       175 | Customer#000000175 |      T2gZ1u7AC2Yve4DnuFWIzbeffURXkBn1PU7 |          10 | 20-427-617-9922 |   1975.35 |    FURNITURE |                                                                                 unts are slyly final foxes. always p |
|       192 | Customer#000000192 |              AnEpYPRNZpiartUaRH7uTU2iTUn |          10 | 20-750-712-2481 |   8239.96 |    MACHINERY |                                                                                   luffily special packages boost car |
|       210 | Customer#000000210 |                   ,XOlfSzkZDAkm96adR41j, |          20 | 30-876-248-9750 |   7250.14 |    HOUSEHOLD |                                                                                es cajole bravely across the blithely |
|       223 | Customer#000000223 |                    MyQxUcG0P QCetmG00GlF |          20 | 30-193-643-1517 |   7476.20 |     BUILDING |             xcuses. silent theodolites across the carefully bold excuses sleep ironic, final courts. regular excuses |
|       228 | Customer#000000228 | rZ1wxvHNByT71bUJWZjXMDROzlAch6FVu,dj8Zfq |          20 | 30-435-915-1603 |   6868.12 |    FURNITURE |                                                                                        es. blithely permanent sentim |
|       231 | Customer#000000231 |                   5lcJkS1RCJaNztx3Dbwp9w |          10 | 20-825-880-1065 |    283.55 |     BUILDING |                    rly accounts. frays boost; furiously regular deposits wake about the slyly bold patterns. special |
|       247 | Customer#000000247 |                       eSAW4XaakYFj2WToKU |          20 | 30-151-905-3513 |   8495.92 |    HOUSEHOLD |                                 tes nag according to the blithe, even packages. sometimes unusual packages integrate |
|       248 | Customer#000000248 |                           FK7ZVASQzfuQmn |          10 | 20-447-727-8914 |   8908.35 |    FURNITURE |                             out the blithely express instructions. furiously unusual deposits sleep. quickly even re |
|       256 | Customer#000000256 |              NhUqKL2JS,iems1ev2gWpioYLG7 |          10 | 20-229-271-4429 |   1299.92 |    HOUSEHOLD |    ously fluffily regular packages. requests are. requests are slyly. packages sleep. silent, final theodolites wake |
|       278 | Customer#000000278 |                         XHAfHlrYQM3elmhJ |          20 | 30-445-570-5841 |   7621.56 |     BUILDING |   ely unusual accounts. stealthily special instructions affix blithely. regular, ironic packages sleep even platelet |
|       285 | Customer#000000285 |      rB6fTQKle64k3MvCCatad8DfMgR5OZA G4r |          20 | 30-235-130-1313 |   7276.72 |    FURNITURE |                  slyly according to the blithely special instructions. ironic ideas against the blithely furious pac |
|       289 | Customer#000000289 |   e6IFMKK,D5dGgXg,84,0qqjoM97YhAhsx7eDk8 |          10 | 20-456-773-7693 |   -215.75 |   AUTOMOBILE |                                                                                    ly even requests about the regula |
|       306 | Customer#000000306 |              rnCcmj VQaPfiCkieUDoxbmbrSZ |          10 | 20-109-305-9629 |   3268.01 |   AUTOMOBILE |                                                                         iously unusual pinto beans nag carefully: bl |
|       321 | Customer#000000321 |          LX0SKs3jqo9wH1yixIdGWp2ItclDiuL |          20 | 30-114-675-9153 |   7718.77 |    FURNITURE |                                 ng the final, bold requests. furiously regular accounts inside the furiously pending |
|       322 | Customer#000000322 |                            Q49touHjVcMk3 |          20 | 30-660-202-7517 |   4489.98 |    HOUSEHOLD |                                               sts-- slyly special platelets cajole blithely blithely pending pinto b |
|       330 | Customer#000000330 |                         7LdPT8Ro7oEzLdXQ |          20 | 30-476-852-2371 |   8244.73 |    MACHINERY |                                                 counts are blithely daringly ironic asymptotes. furiously express as |
|       353 | Customer#000000353 |                NLykoFfWPVAqgNw7MRPIi3sqj |          10 | 20-733-644-2244 |   3199.03 |     BUILDING |                        grate above the slyly final requests. always special foxes haggle thin instructions. slyly sp |
|       356 | Customer#000000356 |                  S9Ld37hIwg8CDfYQBZMkWi7 |          10 | 20-415-457-4421 |   2934.06 |    FURNITURE |                                                                        inal decoys cajole furiously regular accounts |
|       361 | Customer#000000361 |                            G,lSHfh5MUYOP |          20 | 30-164-267-4590 |   7451.84 |     BUILDING |                                                                              ackages engage bold foxes-- slyly final |
|       373 | Customer#000000373 | ZJ arwjGPQeFhos30E5GyKeimsS tdGQqXhkn7Hh |          20 | 30-883-170-4010 |   2354.06 |    MACHINERY |                                         y ironic theodolites. fluffily final theodolites boost carefully slyly final |
|       393 | Customer#000000393 |                   a8mfzH5WWiYflqR6fk2YbM |          20 | 30-749-949-5915 |   3593.57 |    FURNITURE |                                        deposits cajole furiously carefully bold packages. blithely even instructions |
|       405 | Customer#000000405 |    Foadj, hyAIHaRbJQxOYQ1 WBaltNzP1yPnSN |          10 | 20-509-301-7901 |   7519.14 |    MACHINERY | ely unusual accounts sleep fluffily quickly unusual packages. blithely even courts haggle? slyly unusual deposits sl |
|       408 | Customer#000000408 |        8pHPXF0XQMRWhybTXXjnX5nGT97sY2Slp |          10 | 20-177-807-5661 |   6825.37 |     BUILDING |                         ains. special, silent asymptotes against the deposits cajole slyly about the even, special a |
|       420 | Customer#000000420 |                          k5,2pTYe4vSXrRg |          20 | 30-776-366-5869 |   1999.35 |     BUILDING |        er the slyly ironic requests. quickly ironic requests will have to x-ray blithely final excuses. blithely reg |
|       433 | Customer#000000433 |                            U3lxmXrMxaa,v |          20 | 30-659-445-3595 |   8746.23 |    FURNITURE |                                                                      -- regular packages sleep blithely among the fu |
|       445 | Customer#000000445 |   f3Z6q0h6hsjkt4esBYJPgKVNoC5fvzTgdOvnzb |          20 | 30-849-846-6070 |   8018.81 |    FURNITURE |                                        pecial accounts. foxes wake packages. carefully special requests haggle furio |
|       451 | Customer#000000451 |                     2hg7o,oG0p0,L21suNdY |          20 | 30-939-275-3248 |   2110.59 |    HOUSEHOLD |                                                                ously over the instructions. blithely regular excuses |
|       457 | Customer#000000457 |     NQq4Ms5A ,vZT6vIZxsaaPrvaC3u15o48X4L |          20 | 30-543-684-2857 |   5867.61 |    FURNITURE |                       instructions wake carefully after the furiously express deposits. slyly silent ideas boost. bl |
|       468 | Customer#000000468 |                        jOPIJryc54PDzvLum |          10 | 20-489-960-5023 |   9834.19 |    FURNITURE |                                    furiously ironic accounts. requests haggle slyly final requests. regular patterns |
|       470 | Customer#000000470 |            xRrK49xbW4AcHdhaKthyIPdooKaem |          20 | 30-507-458-4433 |   3597.53 |    HOUSEHOLD |                                                     blithely thin excuses. fluffily pending packages sleep carefully |
|       484 | Customer#000000484 |                 JzEsF7s A9f9k4Epm66HHpzI |          20 | 30-777-953-8902 |   4245.00 |     BUILDING |                         nal, ironic gifts are against the blithely final foxes-- quickly quick ideas sleep fluffily. |
|       494 | Customer#000000494 |         lgK7HklFa o14OGNy8AJ2oCBpKEoJGEi |          10 | 20-330-453-6579 |   6295.47 |    FURNITURE |                                                         oxes. express accounts cajole slyly about the special instru |
|       503 | Customer#000000503 | Uuof2lfoBl70yChqibi iPfixgCGSZKriugsQMV1 |          20 | 30-441-755-3094 |   3213.66 |    MACHINERY |                                                                                    leep. slyly quick accounts are. a |
|       504 | Customer#000000504 |    Zkx9uXBcfmb46TLicQ0ro2IgSjxez3afcVns, |          10 | 20-916-264-7594 |      0.51 |    FURNITURE |                                                                    ly final excuses against the sly requests haggle  |
|       517 | Customer#000000517 |         F8CVMjSlWmVgKFUYD4y6TWwLtbHcpKXt |          10 | 20-475-741-4234 |   3959.71 |    FURNITURE |                                                             nst the carefully even theodolites haggle furiously acco |
|       523 | Customer#000000523 |           jMc8Lz8DhJUBv29 ,wVyKIkJLDuT1q |          10 | 20-638-320-5977 |   -275.73 |     BUILDING |                                                               raids integrate silent realms. fluffily express packag |
|       537 | Customer#000000537 |                               wt3wuo0WHO |          10 | 20-337-488-6765 |   2614.79 |    FURNITURE |                          foxes sleep. slyly bold dependencies haggle carefully along the special pinto beans. fluffi |
|       545 | Customer#000000545 |                       rz2vUH0Dn6bOecBnvz |          10 | 20-849-123-8918 |   7505.33 |   AUTOMOBILE |               l foxes sleep furiously across the bold packages. slyly bold instructions among the even, even deposit |
|       591 | Customer#000000591 |                        wkmTqEmyI3UOEoG3q |          20 | 30-584-309-7885 |   6344.66 |    MACHINERY |             xpress deposits. slyly ironic ideas haggle: daringly even requests after the quickly final ideas boost q |
|       634 | Customer#000000634 |              d,R7MIjhU6 sdLEB79rOFQFSsPz |          20 | 30-997-704-1110 |   6397.58 |    FURNITURE |           among the regular foxes. final ideas haggle blithely. carefully express dinos cajole quickly slyly regular |
|       652 | Customer#000000652 |          05Fdg C9ANI6R0Vsas0PLEVzvj0I,gL |          20 | 30-254-389-5987 |   -919.65 |   AUTOMOBILE |                                             ts poach quickly carefully bold asymptotes. fluffily regular foxes about |
|       669 | Customer#000000669 |         RuNcXJQ5t248uDAEvo,BZnuUeEXFnnfB |          10 | 20-471-280-4789 |   6019.20 |    MACHINERY |                                                                                 , final packages doze across the car |
|       675 | Customer#000000675 |                    PQDMvTGcs T9n7ENDAhcE |          20 | 30-299-640-9565 |   5295.26 |    HOUSEHOLD |                                                                               old accounts sleep blithely toward the |
|       679 | Customer#000000679 |           jhLZlG1fRiSE0 wDLOCguVB96dH6a5 |          10 | 20-146-696-9508 |   1394.44 |   AUTOMOBILE |                                                                                    oys. furiously silent pinto beans |
|       681 | Customer#000000681 |       vSVDO8r4WZhmO6apyum0gnrIeecUHWkJWu |          20 | 30-809-878-5822 |    235.53 |    MACHINERY |                            y bold deposits boost slyly among the deposits. quickly regular asymptotes above the care |
|       694 | Customer#000000694 |    Y7ClYkAtlRFmObZbK4rdfd0U0hzlAUvWxZWf8 |          10 | 20-646-375-1939 |   2222.65 |     BUILDING |                                                            . furiously enticing dependencies are furiously quickly i |
|       713 | Customer#000000713 |                           DwrL1iKm8lkbrb |          10 | 20-595-832-3185 |   3829.03 |    MACHINERY |                            ts: carefully ironic asymptotes use furiously express instructions. dependencies across t |
|       718 | Customer#000000718 |                        w0k3o98iWdnjqlbhk |          20 | 30-605-635-8197 |   8438.40 |    HOUSEHOLD |                    boldly pending requests poach furiously. blithely unusual accounts boost blithely carefully bold  |
|       722 | Customer#000000722 |             RtEIx4lt qg79isMPfnwzQHXTuNA |          20 | 30-633-109-9587 |   2724.80 |     BUILDING |                                                 ke slyly before the regular dolphins. special, ironic frets nag slyl |
|       729 | Customer#000000729 |            31upfqqApE5VXKYJQUzWy0eFhX4J4 |          20 | 30-900-572-2883 |   8947.26 |    MACHINERY |              . unusual packages wake furiously after the blithely final deposits-- close gifts until the quickly bol |
|       738 | Customer#000000738 |               JMOPSSs99dNdXgtw18Qb4m4eHt |          10 | 20-722-370-5220 |   2734.95 |    MACHINERY |                                     fully ironic instructions. platelets wake furiously regular platelets. carefully |
|       740 | Customer#000000740 |       moM kCzLz4rzp a8tANsfu6aDQaMEPkgkK |          10 | 20-215-156-3727 |   1733.76 |     BUILDING |                                                                                  ecial requests around the quickly f |
|       743 | Customer#000000743 |     5hrrF6fzl8L1hojkfAv9FwoH4x2Foz0PY7wd |          20 | 30-743-559-7934 |   8450.37 |    HOUSEHOLD |                                                        silent requests. quickly final escapades wake never. bold, bo |
|       746 | Customer#000000746 |                 icgHSeYag6FSkI0mWA3,Mf5t |          20 | 30-154-354-9928 |   1164.46 |    MACHINERY |                                                            ly regular packages. furiously final deposits wake slyly  |
|       765 | Customer#000000765 |              QTvYMOc61dN,a3rYqPXtW9lFe23 |          20 | 30-544-657-7473 |   5683.33 |   AUTOMOBILE |                                                           cross the quickly ironic accounts. special, regular reques |
|       772 | Customer#000000772 |                   8puF90rqjM92F,wugrSHDl |          20 | 30-405-614-4887 |   7555.16 |    MACHINERY |                                  ainments along the furiously unusual deposits wake fluffily dogged, pending dolphin |
|       777 | Customer#000000777 |                           ZTQN74Q5BTR Q4 |          20 | 30-765-163-9750 |   9097.52 |   AUTOMOBILE |                            ual, express accounts haggle slyly across the bold requests. carefully ironic pinto beans |
|       787 | Customer#000000787 |          wvbMYxe11ZEZeEYt,AsnM8WXlcHYdNE |          10 | 20-210-617-3870 |    212.16 |   AUTOMOBILE |                               . ironic deposits wake against the ideas. ironic deposits wake fluffily ironic deposit |
|       805 | Customer#000000805 |       woguVtOjwvC8LLtPRALISNwAOFRf70Pfqk |          10 | 20-732-989-5653 |    511.69 |     BUILDING |            quickly unusual accounts haggle carefully after the even accounts. deposits cajole carefully bravely spec |
|       818 | Customer#000000818 |     pwawgpF2CJSFbHeEK HPpCuAAEBYalJ7MSMm |          20 | 30-943-141-5174 |   -574.39 |     BUILDING |                                             telets about the theodolites nag furiously around the foxes. ironic pack |
|       825 | Customer#000000825 |                gSbRSD0uARnTSGEyQNv02T9vt |          10 | 20-492-863-1129 |   1809.01 |    HOUSEHOLD |                                          ffily final waters sleep accounts. pinto beans against the theodolites wake |

In [47]:
%%sql
-- all customer rows which have do not have c_nationkey as 10 or 20
SELECT
  *
FROM
  customer
WHERE
  c_nationkey NOT IN (10, 20);

+-----------+--------------------+------------------------------------------+-------------+-----------------+-----------+--------------+----------------------------------------------------------------------------------------------------------------------+
| c_custkey |             c_name |                                c_address | c_nationkey |         c_phone | c_acctbal | c_mktsegment |                                                                                                            c_comment |
+-----------+--------------------+------------------------------------------+-------------+-----------------+-----------+--------------+----------------------------------------------------------------------------------------------------------------------+
|         1 | Customer#000000001 |                        j5JsirBM9PsCy0O1m |          15 | 25-989-741-2988 |    711.56 |     BUILDING |                                                       y final requests wake slyly quickly special accounts. blithely |
|         2 | Customer#000000002 |           487LW1dovn6Q4dMVymKwwLE9OKf3QG |          13 | 23-768-687-3665 |    121.65 |   AUTOMOBILE |                                                      y carefully regular foxes. slyly regular requests about the bli |
|         3 | Customer#000000003 |                             fkRGN8nY4pkE |           1 | 11-719-748-3364 |   7498.12 |   AUTOMOBILE |               fully. carefully silent instructions sleep alongside of the slyly regular asymptotes. quickly regular  |
|         4 | Customer#000000004 |                              4u58h fqkyE |           4 | 14-128-190-5944 |   2866.83 |    MACHINERY |                                                                     sublate. fluffily even instructions are about th |
|         5 | Customer#000000005 |             hwBtxkoBF qSW4KrIk5U 2B1AU7H |           3 | 13-750-942-6364 |    794.47 |    HOUSEHOLD |                                                                   equests haggle furiously against the pending packa |
|         7 | Customer#000000007 |           8OkMVLQ1dK6Mbu6WG9 w4pLGQ n7MQ |          18 | 28-190-982-9759 |   9561.95 |   AUTOMOBILE |                                       ounts. ironic, regular accounts sleep. final requests haggle quickly after the |
|         8 | Customer#000000008 |    j,pZ,Qp,qtFEo0r0c 92qobZtlhSuOqbE4JGV |          17 | 27-147-574-9335 |   6819.74 |     BUILDING |    riously final excuses sublate quickly among the fluffily even foxes. quickly final packages haggle furiously furi |
|         9 | Customer#000000009 |               vgIql8H6zoyuLMFNdAMLyE7 H9 |           8 | 18-338-906-3675 |   8324.07 |    FURNITURE |                        ss pinto beans believe slyly quiet deposits-- doggedly bold packages boost. quickly ironic de |
|        10 | Customer#000000010 |       Vf mQ6Ug9Ucf5OKGYq fsaX AtfsO7,rwY |           5 | 15-741-346-9870 |   2753.54 |    HOUSEHOLD |                                                                                      g quickly after the evenly bold |
|        11 | Customer#000000011 |                  cG48rYjF3Aw7xs hKUXXqmI |          23 | 33-464-151-3439 |   -272.60 |     BUILDING |                 ng to the regular foxes. furiously final deposits across the final platelets cajole quickly above th |
|        12 | Customer#000000012 |                            Sb4gxKs7W1AZa |          13 | 23-791-276-1263 |   3396.49 |    HOUSEHOLD |                ickly regular dependencies boost blithely around the slyly ironic theodolites. furiously special dolp |
|        13 | Customer#000000013 |                  Ez3ax0D5HnUbeUVSxoX8a8B |           3 | 13-761-547-5974 |   3857.34 |     BUILDING |                   quickly brave foxes. blithely even packages against the pinto beans boost furiously against the re |
|        14 | Customer#000000014 |                          h3GFMzeFfYiamqr |           1 | 11-845-129-3851 |   5266.30 |    FURNITURE |                                                                                    r, express foxes cajole slyly aga |
|        15 | Customer#000000015 |   3y4KK4CcfNwNCTP0u0p1Rk6aeghe3Z30mo0VnD |          23 | 33-687-542-7601 |   2788.52 |    HOUSEHOLD |                      quests after the furiously ironic platelets are among the express dependencies. carefully even  |
|        17 | Customer#000000017 |   Js JrVHNAyCYMANzPGzvonS8kX8s3 yeLi3u9T |           2 | 12-970-682-3487 |      6.34 |   AUTOMOBILE |                                                                                     fluffily final packages. slyly f |
|        18 | Customer#000000018 |               YyukcsqIxlyuXs702Rd2Rl9D1z |           6 | 16-155-215-1315 |   5494.43 |     BUILDING |                                                    ickly even packages about the unusual dependencies cajole furious |
|        19 | Customer#000000019 |            yO0XPkiuSWk0vN FfcH5 IA3oBYy  |          18 | 28-396-526-5053 |   8914.71 |    HOUSEHOLD |                                     ly final pinto beans boost carefully. furiously unusual requests boost furiously |
|        20 | Customer#000000020 |                            i bGScABFHXdM |          22 | 32-957-234-8742 |   7603.40 |    FURNITURE |                                                uickly regular instructions hang silent dugouts! regular, regular fox |
|        21 | Customer#000000021 |                            42E5BARtqjomD |           8 | 18-902-614-8344 |   1428.25 |    MACHINERY |                                                               e blithely carefully quick sheaves. furiously regular  |
|        22 | Customer#000000022 |             biUBW,0ldzWGT91Doo5b77G6N3Bp |           3 | 13-806-545-9701 |    591.98 |    MACHINERY |                                                                   s. theodolites nag blithely final packages. finall |
|        23 | Customer#000000023 |          dN2r4,XdTpNXcoVfBKLEP2zz,5DU7g8 |           3 | 13-312-472-8245 |   3332.02 |    HOUSEHOLD |                               furiously regular accounts haggle slyly. special sauternes hinder carefully. fluffily  |
|        24 | Customer#000000024 |     k3qlKjqtHuzNAvIFyZX2Yc1crXuMfMU6SbAl |          13 | 23-127-851-8031 |   9255.67 |    MACHINERY |                                                                     s. final hockey players snooze carefully furious |
|        25 | Customer#000000025 |                    kBSktmaKkjm28IFkVypLN |          12 | 22-603-468-3533 |   7133.70 |    FURNITURE |         theodolites nag furiously along the asymptotes. furiously special ideas detect. carefully regular instructio |
|        26 | Customer#000000026 |                          TFH OW1MeFU6OIb |          22 | 32-363-455-4837 |   5182.05 |   AUTOMOBILE |                                               gainst the express theodolites. deposits sleep furiously. regular, spe |
|        27 | Customer#000000027 |                        j8SkiuuBp gBe7,yT |           3 | 13-137-193-2709 |   5679.84 |     BUILDING |                                                                      permanently. slyly ironic dependencies integrat |
|        28 | Customer#000000028 |               J5tK,OQa07KQSuY5b4qRFYVYRF |           8 | 18-774-241-1462 |   1007.18 |    FURNITURE |                                                                     r accounts are quickly. boldly bold foxes haggle |
|        29 | Customer#000000029 |         hVQNzLtqGpgUXNMY0wlZVstaf52mXXxJ |           0 | 10-773-203-7342 |   7618.27 |    FURNITURE |                                                                nod furiously after the final accounts. courts nag qu |
|        30 | Customer#000000030 |  EhnzmgkqQw7UXhF0PVdg gLfSAihaaHaD2fZah2 |           1 | 11-764-165-5076 |   9321.01 |     BUILDING |                                                                    ep quickly slyly express accounts-- carefully eve |
|        31 | Customer#000000031 |            g6qoPd,wIQrwUM3dqMP unpruI5zy |          23 | 33-197-837-7094 |   5236.89 |    HOUSEHOLD |                                                                                the bold, silent pinto beans. slyly s |
|        32 | Customer#000000032 |    InYu1tIr6EjN0nozdpf3hHRA,8FBYIbU1OcYh |          15 | 25-430-914-2194 |   3471.53 |     BUILDING |                                                                     lly carefully unusual accounts. final attainment |
|        33 | Customer#000000033 |            Bl8FeyfxOpFuRuDEVIPYPz46vNKrn |          17 | 27-375-391-1280 |    -78.56 |   AUTOMOBILE |                                                  , unusual accounts. closely ironic dependencies are slyly. blithely |
|        34 | Customer#000000034 |               bUkRv2UNDOtEycuW,RuKn0eYg6 |          15 | 25-344-968-5422 |   8589.70 |    HOUSEHOLD |                                                                        s. furiously final asymptotes wake. ironic fo |
|        35 | Customer#000000035 |                            8mH4knWDpsifY |          17 | 27-566-888-7431 |   1228.24 |    HOUSEHOLD |                                                               cies with the carefully regular sauternes engage caref |
|        36 | Customer#000000036 |                    Y7wosIxbsBi,0nNiSG4V7 |          21 | 31-704-669-5769 |   4987.27 |     BUILDING |                                   ys among the accounts affix blithely asymptotes. carefully even deposits are fluff |
|        37 | Customer#000000037 |                        Um5WbwJ0X8QCOy75y |           8 | 18-385-235-7162 |   -917.75 |    FURNITURE |                                                            above the slyly regular accounts sleep along the carefull |
|        38 | Customer#000000038 |                     RVmMVNRVUSaS9fbsYQBT |          12 | 22-306-880-7212 |   6345.11 |    HOUSEHOLD |       ke slyly; deposits thrash doggedly. regular platelets use fluffily. thinly regular pinto beans eat carefully a |
|        39 | Customer#000000039 |                EDP9K1bwtXYNLGCA2mrlOM1U, |           2 | 12-387-467-6509 |   6264.31 |   AUTOMOBILE |                                                                                     eposits play across the furiousl |
|        40 | Customer#000000040 |                           LcDk4rtJ85,CLw |           3 | 13-652-915-8939 |   1335.30 |     BUILDING |                                                     y. brave accounts wake slyly ironic epitaphs; express packages h |
|        42 | Customer#000000042 |                               tI8 wutpGM |           5 | 15-416-330-4175 |   8727.01 |     BUILDING |         lphins. blithely bold requests about the special patterns detect quickly regular foxes. furiously express in |
|        43 | Customer#000000043 |        Dx8PHkGSFJWLg3XtkzCX28iHRrQXbCRlN |          19 | 29-316-665-2897 |   9904.28 |    MACHINERY |               ronic pinto beans. packages sleep. furiously ruthless packages print blithely fluffily even platelets. |
|        44 | Customer#000000044 |        dI0Nc9bvnxXHCWu10bSVn,NEJ2kwdyqvI |          16 | 26-190-260-5375 |   7315.94 |   AUTOMOBILE |                                                                                fily regular asymptotes. ironic, pend |
|        45 | Customer#000000045 |                  XwXcOClKCcFek0oQDl0WFNo |           9 | 19-715-298-9917 |   9983.38 |   AUTOMOBILE |                                                                                l excuses are busy accounts. blithely |
|        46 | Customer#000000046 |                              NQ7345EZ,fS |           6 | 16-357-681-2007 |   5744.59 |   AUTOMOBILE |        equests integrate fluffily after the carefully special accounts. fluffily regular deposits eat slyly ironic,  |
|        47 | Customer#000000047 |                      Q,6KCP8Am4WrKN5QJd7 |           2 | 12-427-271-9466 |    274.58 |     BUILDING |                                                rding to the final deposits. furiously ironic packages cajole slyly a |
|        48 | Customer#000000048 |                         076rIcJpxBmwMEdq |           0 | 10-508-348-5882 |   3792.50 |     BUILDING |                                   carefully. furiously bold accounts sleep slyly above the even accounts. ironic acc |
|        50 | Customer#000000050 |                     S8sn2GGsuputhZaN7irC |           6 | 16-658-112-3221 |   4266.13 |    MACHINERY |                                                    ideas cajole. carefully even warthogs affix ironically quickly re |
|        51 | Customer#000000051 |                              y90vmRI7wCX |          12 | 22-344-885-4251 |    855.87 |    FURNITURE |                                            across the express, bold requests. closely final accounts sleep blithely  |
|        52 | Customer#000000052 |              UracAlAA8tSHL5V,poTZIOjh8o, |          11 | 21-186-284-5998 |   5630.28 |    HOUSEHOLD |                                            ts boost. carefully express waters across the blithely regular foxes inte |
|        53 | Customer#000000053 |       kDQujt7Ll72zSexpBht7Q1WToFWvlcdKIP |          15 | 25-168-852-5363 |   4113.64 |    HOUSEHOLD |                                            ts. carefully regular ideas across the blithely final packages cajole car |
|        54 | Customer#000000054 |                    1GWwLsVwmol4lt0KCz7m1 |           4 | 14-776-370-4745 |    868.90 |   AUTOMOBILE |            are slyly. instructions sublate slyly. fluffily even packages among the slyly regular accounts hang along |
|        57 | Customer#000000057 |                           ST32P xcb94b46 |          21 | 31-835-306-1650 |   4151.93 |   AUTOMOBILE |                                          thely pending deposits. packages cajole blithely slyly express requests. fl |
|        58 | Customer#000000058 |          LRQBToGZ8wSLO3m5HBe2Cp1i97CJIr8 |          13 | 23-244-493-2508 |   6478.46 |    HOUSEHOLD |                       ronic accounts dazzle quickly along the blithely special packages. blithely final pinto beans  |
|        59 | Customer#000000059 |                   tfcob0wJRYdypIJLzBckGW |           1 | 11-355-584-3112 |   3458.60 |    MACHINERY |                                              s asymptotes wake. slyly ironic deposits haggle furiously; slyly regula |
|        60 | Customer#000000060 |                     mtCNJIveoJ 1E6sUhs,j |          12 | 22-480-575-5866 |   2741.87 |    MACHINERY |                        ts. accounts cajole carefully. carefully final requests across the even accounts affix slyly  |
|        61 | Customer#000000061 |  SGDNwNWmqhvJKXwNlrpL4 TqAdz7XRDrKyAIQ2m |          17 | 27-626-559-8599 |   1536.24 |    FURNITURE |                                                                      slyly. quickly unusual deposits haggle furiousl |
|        62 | Customer#000000062 |                              yBhgYoDvZX1 |           7 | 17-361-978-7059 |    595.61 |    MACHINERY |                                e carefully final requests. fluffily regular deposits haggle among the ironic warhors |
|        63 | Customer#000000063 |                           j398B6441 Rgii |          21 | 31-952-552-9584 |   9331.13 |   AUTOMOBILE |                                                              ar pinto beans nag furiously furiously regular ideas. d |
|        64 | Customer#000000064 |                    fPoMk3Y,GQhgXCQGhn0c8 |           3 | 13-558-731-7204 |   -646.64 |     BUILDING |                                                            hely unusual deposits sleep furiously express requests. c |
|        65 | Customer#000000065 | ak7rtta,tWG,jR,cTSXflW6RVQ3alna3P4Q,zF03 |          23 | 33-733-623-5267 |   8795.16 |   AUTOMOBILE |                                                  ironic courts sleep slyly above the ironic, bold accounts. blithely |
|        66 | Customer#000000066 |                       4PzmA4jZm7Qh22yrZq |          22 | 32-213-373-5094 |    242.77 |    HOUSEHOLD |                                                                   nic instructions are furiously unusual, unusual pa |
|        67 | Customer#000000067 |                ALk,OdKy V5SruigGvBRMBo8S |           9 | 19-403-114-4356 |   8166.59 |    MACHINERY |                                                                                    special sentiments. pending depen |
|        68 | Customer#000000068 |                     DSqIPPo9G3xalJSKl0TC |          12 | 22-918-832-2411 |   6853.37 |    HOUSEHOLD |                                                             e slyly express theodolites kindle fluffily ironic, pend |
|        69 | Customer#000000069 | gyuZTEcR4vKyNPMSa15ueKbRS6Tu4RUxw8j,B mv |           9 | 19-225-978-5670 |   1709.28 |    HOUSEHOLD |   sauternes against the silent foxes are slyly quickly special deposits. slyly final foxes integrate furiously. care |
|        70 | Customer#000000070 |        FlCviyJDjHCYkHoJ22QwH4rG6wcHiQ8oa |          22 | 32-828-107-2832 |   4867.52 |    FURNITURE |                           le through the carefully unusual accounts. excuses use slyly. furiously pending accounts a |
|        71 | Customer#000000071 | 8FkQFLN34pFe50URKft43ntisSegsO3SKF0wUyZp |           7 | 17-710-812-5403 |   -611.19 |    HOUSEHOLD |                                               e slyly about the slyly bold theodolites. furiously regular deposits a |
|        72 | Customer#000000072 |  CxyHFFzGum1sz0jBMiqR5AxTNKKjVp6ovnvkjOL |           2 | 12-759-144-9689 |   -362.86 |    FURNITURE |                                                     dolites print blithely about the ironic requests. regular, expre |
|        73 | Customer#000000073 |                      TiJiuAMxW6LUyyVFCKW |           0 | 10-473-439-3214 |   4288.50 |     BUILDING |                                                                 carefully pending packages to the pearls affix quick |
|        74 | Customer#000000074 |          jGhjorX17JmTAfT6gO 6sD9fF1GtFLs |           4 | 14-199-862-7209 |   2764.43 |    MACHINERY |                                                    ithely special excuses. regular deposits cajole furiously finally |
|        75 | Customer#000000075 |               oJrUH20Ovu5fgaLagGIkAswUBF |          18 | 28-247-803-9025 |   6684.10 |   AUTOMOBILE |                       ronic foxes after the brave hockey players haggle after the slyly ironic courts. even, regular |
|        76 | Customer#000000076 |              FXzPoxHecjuQcCLk0Mr6HkbyAPW |           0 | 10-349-718-3044 |   5745.33 |    FURNITURE | es snooze about the accounts. furiously unusual excuses sleep furiously around the blithely careful decoys. express, |
|        77 | Customer#000000077 |                   XyqmVhNelkoWPtjz3lRYxu |          17 | 27-269-357-4674 |   1738.87 |     BUILDING |                 slyly. furiously final accounts sleep slyly among the ironic packages. quickly pending deposits inte |
|        78 | Customer#000000078 |             kpcyQ11dABLX6YO9f,GPALyGbws3 |           9 | 19-960-700-9191 |   7136.97 |    FURNITURE |                                                                                    uriously above the slyly final de |
|        79 | Customer#000000079 |                   EVJjYMyG59w4SINzn0pEfY |          15 | 25-147-850-4166 |   5121.28 |    MACHINERY |  iously even pinto beans hinder final deposits. carefully final accounts along the final theodolites integrate caref |
|        80 | Customer#000000080 |                              h0wy3CSA2ps |           0 | 10-267-172-7101 |   7383.53 |    FURNITURE |                                       ld, bold excuses sleep finally furiously pending pinto beans. furiously expres |
|        82 | Customer#000000082 |               tJkXm2PQBWPRRYkIXPg0YdM03E |          18 | 28-159-442-5305 |   9468.34 |   AUTOMOBILE |                                                               old requests. slyly bold courts sleep carefully packag |

In [48]:
%%sql
SELECT
  COUNT(*)
FROM
  customer;

+----------+
| count(1) |
+----------+
|    15000 |
+----------+

In [49]:
%%sql
SELECT
  COUNT(*)
FROM
  lineitem;

+----------+
| count(1) |
+----------+
|   600572 |
+----------+

In [50]:
%%sql
-- Will show the first ten customer records with the lowest custkey
-- rows are ordered in ASC order by default
SELECT
  *
FROM
  orders
ORDER BY
  o_custkey
LIMIT
  10;

+------------+-----------+---------------+--------------+-------------+-----------------+-----------------+----------------+-------------------------------------------------------------------------------+
| o_orderkey | o_custkey | o_orderstatus | o_totalprice | o_orderdate | o_orderpriority |         o_clerk | o_shippriority |                                                                     o_comment |
+------------+-----------+---------------+--------------+-------------+-----------------+-----------------+----------------+-------------------------------------------------------------------------------+
|      36422 |         1 |             O |    268835.44 |  1997-03-04 |        3-MEDIUM | Clerk#000000532 |              0 |                       s. slyly regular platelets doubt slyly after the thinly |
|     224167 |         1 |             O |     81485.84 |  1996-05-08 |           5-LOW | Clerk#000000657 |              0 |        ithely unusual deposits. slyly pending somas wake quickly according to |
|     135943 |         1 |             F |    263247.54 |  1993-06-22 | 4-NOT SPECIFIED | Clerk#000000685 |              0 |                                               ironic ideas affix furiously ac |
|     164711 |         1 |             F |    283261.47 |  1992-04-26 |        3-MEDIUM | Clerk#000000361 |              0 |                                                  fully special ideas. fluffil |
|     287619 |         1 |             O |     11925.85 |  1996-12-26 |           5-LOW | Clerk#000000854 |              0 | t pending requests. carefully ironic sheaves among the slyly final asymptotes |
|     385825 |         1 |             O |    235155.22 |  1995-11-01 |          2-HIGH | Clerk#000000465 |              0 |               ly express accounts. special requests according to the carefull |
|     430243 |         1 |             F |     35523.05 |  1994-12-24 | 4-NOT SPECIFIED | Clerk#000000121 |              0 |                               e slyly along the furiously pending attainments |
|     454791 |         1 |             F |     83779.26 |  1992-04-19 |        1-URGENT | Clerk#000000815 |              0 |                                    ccounts sleep carefully along the slyly ev |
|     579908 |         1 |             O |     45744.09 |  1996-12-09 |           5-LOW | Clerk#000000783 |              0 |  t packages hinder bold, even dolphins. slyly ironic packages wake fluffily a |
|      52263 |         2 |             F |     36433.77 |  1994-05-08 | 4-NOT SPECIFIED | Clerk#000000080 |              0 |       uests dazzle blithely against the final, final requests. regular theodo |
+------------+-----------+---------------+--------------+-------------+-----------------+-----------------+----------------+-------------------------------------------------------------------------------+

In [51]:
%%sql
-- Will show the first ten customer's records with the highest custkey
SELECT
  *
FROM
  orders
ORDER BY
  o_custkey DESC
LIMIT
  10;

+------------+-----------+---------------+--------------+-------------+-----------------+-----------------+----------------+---------------------------------------------------------------------+
| o_orderkey | o_custkey | o_orderstatus | o_totalprice | o_orderdate | o_orderpriority |         o_clerk | o_shippriority |                                                           o_comment |
+------------+-----------+---------------+--------------+-------------+-----------------+-----------------+----------------+---------------------------------------------------------------------+
|     134848 |     14999 |             O |    170212.14 |  1998-03-07 |          2-HIGH | Clerk#000000669 |              0 |      uests alongside of the ironic, ironic instructions use above t |
|     129605 |     14999 |             P |    172005.93 |  1995-03-27 |        3-MEDIUM | Clerk#000000578 |              0 |                         ffix sometimes. regular ideas haggle carefu |
|      94817 |     14999 |             F |    193676.15 |  1992-08-02 | 4-NOT SPECIFIED | Clerk#000000650 |              0 |     d pearls. asymptotes haggle furiously regular ideas. furiously  |
|      67298 |     14999 |             O |    296795.91 |  1995-09-15 |        1-URGENT | Clerk#000000213 |              0 |                                    carefully bold requests. careful |
|     157894 |     14999 |             F |     76068.72 |  1992-06-08 | 4-NOT SPECIFIED | Clerk#000000952 |              0 | olites. unusual multipliers nag slyly even dependencies. slyly spec |
|     158657 |     14999 |             O |    164096.58 |  1998-02-28 |        3-MEDIUM | Clerk#000000977 |              0 |   eposits haggle slyly? blithely final packages about the regular p |
|     178087 |     14999 |             F |    320537.50 |  1994-04-16 |           5-LOW | Clerk#000000872 |              0 |                 l asymptotes nag stealthily. fluffily ironic reques |
|     190498 |     14999 |             O |    102768.22 |  1998-03-13 |           5-LOW | Clerk#000000941 |              0 |  n foxes. theodolites integrate blithely. final packages lose quick |
|     215168 |     14999 |             F |    202248.65 |  1992-02-24 |          2-HIGH | Clerk#000000633 |              0 |                                         use quickly regular request |
|     233956 |     14999 |             F |    219593.16 |  1994-03-28 |           5-LOW | Clerk#000000719 |              0 |                             pinto beans. regular pinto beans along  |
+------------+-----------+---------------+--------------+-------------+-----------------+-----------------+----------------+---------------------------------------------------------------------+

In [52]:
%%sql
SELECT
  o.o_orderkey,
  l.l_orderkey
FROM
  orders o
  JOIN lineitem l ON o.o_orderkey = l.l_orderkey
  AND o.o_orderdate BETWEEN l.l_shipdate - INTERVAL '5' DAY AND l.l_shipdate  + INTERVAL '5' DAY
LIMIT
  100;

+------------+------------+
| o_orderkey | l_orderkey |
+------------+------------+
|          7 |          7 |
|         32 |         32 |
|         33 |         33 |
|         69 |         69 |
|         71 |         71 |
|        132 |        132 |
|        133 |        133 |
|        198 |        198 |
|        259 |        259 |
|        260 |        260 |
|        288 |        288 |
|        353 |        353 |
|        354 |        354 |
|        420 |        420 |
|        482 |        482 |
|        485 |        485 |
|        486 |        486 |
|        512 |        512 |
|        517 |        517 |
|        548 |        548 |
|        576 |        576 |
|        576 |        576 |
|        581 |        581 |
|        614 |        614 |
|        673 |        673 |
|        678 |        678 |
|        679 |        679 |
|        737 |        737 |
|        739 |        739 |
|        770 |        770 |
|        771 |        771 |
|        771 |        771 |
|        772 |        772 |
|        774 |        774 |
|        802 |        802 |
|        802 |        802 |
|        865 |        865 |
|        871 |        871 |
|        899 |        899 |
|        930 |        930 |
|        930 |        930 |
|        962 |        962 |
|        962 |        962 |
|        992 |        992 |
|        992 |        992 |
|       1027 |       1027 |
|       1088 |       1088 |
|       1094 |       1094 |
|       1095 |       1095 |
|       1095 |       1095 |
|       1120 |       1120 |
|       1127 |       1127 |
|       1186 |       1186 |
|       1252 |       1252 |
|       1284 |       1284 |
|       1287 |       1287 |
|       1314 |       1314 |
|       1347 |       1347 |
|       1410 |       1410 |
|       1506 |       1506 |
|       1506 |       1506 |
|       1571 |       1571 |
|       1573 |       1573 |
|       1574 |       1574 |
|       1600 |       1600 |
|       1605 |       1605 |
|       1606 |       1606 |
|       1639 |       1639 |
|       1639 |       1639 |
|       1664 |       1664 |
|       1667 |       1667 |
|       1667 |       1667 |
|       1671 |       1671 |
|       1735 |       1735 |
|       1767 |       1767 |
|       1794 |       1794 |
|       1824 |       1824 |
|       1825 |       1825 |
|       1856 |       1856 |
|       1891 |       1891 |
|       1923 |       1923 |
|       1954 |       1954 |
|       1956 |       1956 |
|       1985 |       1985 |
|       1991 |       1991 |
|       2054 |       2054 |
|       2081 |       2081 |
|       2084 |       2084 |
|       2146 |       2146 |
|       2182 |       2182 |
|       2208 |       2208 |
|       2208 |       2208 |
|       2209 |       2209 |
|       2241 |       2241 |
|       2241 |       2241 |
|       2273 |       2273 |
|       2273 |       2273 |
|       2274 |       2274 |
|       2279 |       2279 |
|       2306 |       2306 |
+------------+------------+

In [53]:
%%sql
SELECT
  COUNT(o.o_orderkey) AS order_rows_count,
  COUNT(l.l_orderkey) AS lineitem_rows_count
FROM
  orders o
  JOIN lineitem l ON o.o_orderkey = l.l_orderkey
  AND o.o_orderdate BETWEEN l.l_shipdate - INTERVAL '5' DAY AND l.l_shipdate  + INTERVAL '5' DAY;

+------------------+---------------------+
| order_rows_count | lineitem_rows_count |
+------------------+---------------------+
|            24613 |               24613 |
+------------------+---------------------+

In [54]:
%%sql
SELECT
  o.o_orderkey,
  l.l_orderkey
FROM
  orders o
  LEFT JOIN lineitem l ON o.o_orderkey = l.l_orderkey
  AND o.o_orderdate BETWEEN l.l_shipdate - INTERVAL '5' DAY AND l.l_shipdate  + INTERVAL '5' DAY
LIMIT
  100;

+------------+------------+
| o_orderkey | l_orderkey |
+------------+------------+
|          1 |       None |
|          2 |       None |
|          3 |       None |
|          4 |       None |
|          5 |       None |
|          6 |       None |
|          7 |          7 |
|         32 |         32 |
|         33 |         33 |
|         34 |       None |
|         35 |       None |
|         36 |       None |
|         37 |       None |
|         38 |       None |
|         39 |       None |
|         64 |       None |
|         65 |       None |
|         66 |       None |
|         67 |       None |
|         68 |       None |
|         69 |         69 |
|         70 |       None |
|         71 |         71 |
|         96 |       None |
|         97 |       None |
|         98 |       None |
|         99 |       None |
|        100 |       None |
|        101 |       None |
|        102 |       None |
|        103 |       None |
|        128 |       None |
|        129 |       None |
|        130 |       None |
|        131 |       None |
|        132 |        132 |
|        133 |        133 |
|        134 |       None |
|        135 |       None |
|        160 |       None |
|        161 |       None |
|        162 |       None |
|        163 |       None |
|        164 |       None |
|        165 |       None |
|        166 |       None |
|        167 |       None |
|        192 |       None |
|        193 |       None |
|        194 |       None |
|        195 |       None |
|        196 |       None |
|        197 |       None |
|        198 |        198 |
|        199 |       None |
|        224 |       None |
|        225 |       None |
|        226 |       None |
|        227 |       None |
|        228 |       None |
|        229 |       None |
|        230 |       None |
|        231 |       None |
|        256 |       None |
|        257 |       None |
|        258 |       None |
|        259 |        259 |
|        260 |        260 |
|        261 |       None |
|        262 |       None |
|        263 |       None |
|        288 |        288 |
|        289 |       None |
|        290 |       None |
|        291 |       None |
|        292 |       None |
|        293 |       None |
|        294 |       None |
|        295 |       None |
|        320 |       None |
|        321 |       None |
|        322 |       None |
|        323 |       None |
|        324 |       None |
|        325 |       None |
|        326 |       None |
|        327 |       None |
|        352 |       None |
|        353 |        353 |
|        354 |        354 |
|        355 |       None |
|        356 |       None |
|        357 |       None |
|        358 |       None |
|        359 |       None |
|        384 |       None |
|        385 |       None |
|        386 |       None |
|        387 |       None |
|        388 |       None |
+------------+------------+

In [55]:
%%sql
SELECT
  COUNT(o.o_orderkey) AS order_rows_count,
  COUNT(l.l_orderkey) AS lineitem_rows_count
FROM
  orders o
  LEFT JOIN lineitem l ON o.o_orderkey = l.l_orderkey
  AND o.o_orderdate BETWEEN l.l_shipdate - INTERVAL '5' DAY AND l.l_shipdate  + INTERVAL '5' DAY;

+------------------+---------------------+
| order_rows_count | lineitem_rows_count |
+------------------+---------------------+
|           151933 |               24613 |
+------------------+---------------------+

In [56]:
%%sql
SELECT
  o.o_orderkey,
  l.l_orderkey
FROM
  orders o
  RIGHT JOIN lineitem l ON o.o_orderkey = l.l_orderkey
  AND o.o_orderdate BETWEEN l.l_shipdate - INTERVAL '5' DAY AND l.l_shipdate  + INTERVAL '5' DAY
LIMIT
  100;

+------------+------------+
| o_orderkey | l_orderkey |
+------------+------------+
|       None |          1 |
|       None |          1 |
|       None |          1 |
|       None |          1 |
|       None |          1 |
|       None |          1 |
|       None |          2 |
|       None |          3 |
|       None |          3 |
|       None |          3 |
|       None |          3 |
|       None |          3 |
|       None |          3 |
|       None |          4 |
|       None |          5 |
|       None |          5 |
|       None |          5 |
|       None |          6 |
|       None |          7 |
|       None |          7 |
|          7 |          7 |
|       None |          7 |
|       None |          7 |
|       None |          7 |
|       None |          7 |
|       None |         32 |
|       None |         32 |
|       None |         32 |
|       None |         32 |
|       None |         32 |
|         32 |         32 |
|         33 |         33 |
|       None |         33 |
|       None |         33 |
|       None |         33 |
|       None |         34 |
|       None |         34 |
|       None |         34 |
|       None |         35 |
|       None |         35 |
|       None |         35 |
|       None |         35 |
|       None |         35 |
|       None |         35 |
|       None |         36 |
|       None |         37 |
|       None |         37 |
|       None |         37 |
|       None |         38 |
|       None |         39 |
|       None |         39 |
|       None |         39 |
|       None |         39 |
|       None |         39 |
|       None |         39 |
|       None |         64 |
|       None |         65 |
|       None |         65 |
|       None |         65 |
|       None |         66 |
|       None |         66 |
|       None |         67 |
|       None |         67 |
|       None |         67 |
|       None |         67 |
|       None |         67 |
|       None |         67 |
|       None |         68 |
|       None |         68 |
|       None |         68 |
|       None |         68 |
|       None |         68 |
|       None |         68 |
|       None |         68 |
|       None |         69 |
|       None |         69 |
|       None |         69 |
|         69 |         69 |
|       None |         69 |
|       None |         69 |
|       None |         70 |
|       None |         70 |
|       None |         70 |
|       None |         70 |
|       None |         70 |
|       None |         70 |
|       None |         71 |
|       None |         71 |
|       None |         71 |
|       None |         71 |
|         71 |         71 |
|       None |         71 |
|       None |         96 |
|       None |         96 |
|       None |         97 |
|       None |         97 |
|       None |         97 |
|       None |         98 |
|       None |         98 |
|       None |         98 |
+------------+------------+

In [57]:
%%sql
SELECT
  COUNT(o.o_orderkey) AS order_rows_count,
  COUNT(l.l_orderkey) AS lineitem_rows_count
FROM
  orders o
  RIGHT JOIN lineitem l ON o.o_orderkey = l.l_orderkey
  AND o.o_orderdate BETWEEN l.l_shipdate - INTERVAL '5' DAY AND l.l_shipdate  + INTERVAL '5' DAY;

+------------------+---------------------+
| order_rows_count | lineitem_rows_count |
+------------------+---------------------+
|            24613 |              600572 |
+------------------+---------------------+

In [58]:
%%sql
SELECT
  o.o_orderkey,
  l.l_orderkey
FROM
  orders o
  FULL OUTER JOIN lineitem l ON o.o_orderkey = l.l_orderkey
  AND o.o_orderdate BETWEEN l.l_shipdate - INTERVAL '5' DAY AND l.l_shipdate  + INTERVAL '5' DAY
LIMIT
  100;

+------------+------------+
| o_orderkey | l_orderkey |
+------------+------------+
|          7 |          7 |
|       None |          7 |
|       None |          7 |
|       None |          7 |
|       None |          7 |
|       None |          7 |
|       None |          7 |
|         32 |         32 |
|       None |         32 |
|       None |         32 |
|       None |         32 |
|       None |         32 |
|       None |         32 |
|         34 |       None |
|       None |         34 |
|       None |         34 |
|       None |         34 |
|         39 |       None |
|       None |         39 |
|       None |         39 |
|       None |         39 |
|       None |         39 |
|       None |         39 |
|       None |         39 |
|         65 |       None |
|       None |         65 |
|       None |         65 |
|       None |         65 |
|         98 |       None |
|       None |         98 |
|       None |         98 |
|       None |         98 |
|       None |         98 |
|        130 |       None |
|       None |        130 |
|       None |        130 |
|       None |        130 |
|       None |        130 |
|       None |        130 |
|        167 |       None |
|       None |        167 |
|       None |        167 |
|        196 |       None |
|       None |        196 |
|       None |        196 |
|        198 |        198 |
|       None |        198 |
|       None |        198 |
|       None |        198 |
|       None |        198 |
|        228 |       None |
|       None |        228 |
|        229 |       None |
|       None |        229 |
|       None |        229 |
|       None |        229 |
|       None |        229 |
|       None |        229 |
|       None |        229 |
|        262 |       None |
|       None |        262 |
|       None |        262 |
|       None |        262 |
|        293 |       None |
|       None |        293 |
|       None |        293 |
|       None |        293 |
|        325 |       None |
|       None |        325 |
|       None |        325 |
|       None |        325 |
|        326 |       None |
|       None |        326 |
|       None |        326 |
|       None |        326 |
|       None |        326 |
|       None |        326 |
|       None |        326 |
|       None |        326 |
|        385 |       None |
|       None |        385 |
|       None |        385 |
|        386 |       None |
|       None |        386 |
|       None |        386 |
|       None |        386 |
|        388 |       None |
|       None |        388 |
|       None |        388 |
|       None |        388 |
|        417 |       None |
|       None |        417 |
|       None |        417 |
|       None |        417 |
|       None |        417 |
|        418 |       None |
|       None |        418 |
|       None |        418 |
|       None |        418 |
|        420 |        420 |
+------------+------------+

In [59]:
%%sql
SELECT
  COUNT(o.o_orderkey) AS order_rows_count,
  COUNT(l.l_orderkey) AS lineitem_rows_count
FROM
  orders o
  FULL OUTER JOIN lineitem l ON o.o_orderkey = l.l_orderkey
  AND o.o_orderdate BETWEEN l.l_shipdate - INTERVAL '5' DAY AND l.l_shipdate  + INTERVAL '5' DAY;

+------------------+---------------------+
| order_rows_count | lineitem_rows_count |
+------------------+---------------------+
|           151933 |              600572 |
+------------------+---------------------+

In [60]:
%%sql
SELECT
  n.n_name AS nation_c_name,
  r.r_name AS region_c_name
FROM
  nation n
  CROSS JOIN region r;

+---------------+---------------+
| nation_c_name | region_c_name |
+---------------+---------------+
|       ALGERIA |        AFRICA |
|       ALGERIA |       AMERICA |
|       ALGERIA |          ASIA |
|       ALGERIA |        EUROPE |
|       ALGERIA |   MIDDLE EAST |
|     ARGENTINA |        AFRICA |
|     ARGENTINA |       AMERICA |
|     ARGENTINA |          ASIA |
|     ARGENTINA |        EUROPE |
|     ARGENTINA |   MIDDLE EAST |
|        BRAZIL |        AFRICA |
|        BRAZIL |       AMERICA |
|        BRAZIL |          ASIA |
|        BRAZIL |        EUROPE |
|        BRAZIL |   MIDDLE EAST |
|        CANADA |        AFRICA |
|        CANADA |       AMERICA |
|        CANADA |          ASIA |
|        CANADA |        EUROPE |
|        CANADA |   MIDDLE EAST |
|         EGYPT |        AFRICA |
|         EGYPT |       AMERICA |
|         EGYPT |          ASIA |
|         EGYPT |        EUROPE |
|         EGYPT |   MIDDLE EAST |
|      ETHIOPIA |        AFRICA |
|      ETHIOPIA |       AMERICA |
|      ETHIOPIA |          ASIA |
|      ETHIOPIA |        EUROPE |
|      ETHIOPIA |   MIDDLE EAST |
|        FRANCE |        AFRICA |
|        FRANCE |       AMERICA |
|        FRANCE |          ASIA |
|        FRANCE |        EUROPE |
|        FRANCE |   MIDDLE EAST |
|       GERMANY |        AFRICA |
|       GERMANY |       AMERICA |
|       GERMANY |          ASIA |
|       GERMANY |        EUROPE |
|       GERMANY |   MIDDLE EAST |
|         INDIA |        AFRICA |
|         INDIA |       AMERICA |
|         INDIA |          ASIA |
|         INDIA |        EUROPE |
|         INDIA |   MIDDLE EAST |
|     INDONESIA |        AFRICA |
|     INDONESIA |       AMERICA |
|     INDONESIA |          ASIA |
|     INDONESIA |        EUROPE |
|     INDONESIA |   MIDDLE EAST |
|          IRAN |        AFRICA |
|          IRAN |       AMERICA |
|          IRAN |          ASIA |
|          IRAN |        EUROPE |
|          IRAN |   MIDDLE EAST |
|          IRAQ |        AFRICA |
|          IRAQ |       AMERICA |
|          IRAQ |          ASIA |
|          IRAQ |        EUROPE |
|          IRAQ |   MIDDLE EAST |
|         JAPAN |        AFRICA |
|         JAPAN |       AMERICA |
|         JAPAN |          ASIA |
|         JAPAN |        EUROPE |
|         JAPAN |   MIDDLE EAST |
|        JORDAN |        AFRICA |
|        JORDAN |       AMERICA |
|        JORDAN |          ASIA |
|        JORDAN |        EUROPE |
|        JORDAN |   MIDDLE EAST |
|         KENYA |        AFRICA |
|         KENYA |       AMERICA |
|         KENYA |          ASIA |
|         KENYA |        EUROPE |
|         KENYA |   MIDDLE EAST |
|       MOROCCO |        AFRICA |
|       MOROCCO |       AMERICA |
|       MOROCCO |          ASIA |
|       MOROCCO |        EUROPE |
|       MOROCCO |   MIDDLE EAST |
|    MOZAMBIQUE |        AFRICA |
|    MOZAMBIQUE |       AMERICA |
|    MOZAMBIQUE |          ASIA |
|    MOZAMBIQUE |        EUROPE |
|    MOZAMBIQUE |   MIDDLE EAST |
|          PERU |        AFRICA |
|          PERU |       AMERICA |
|          PERU |          ASIA |
|          PERU |        EUROPE |
|          PERU |   MIDDLE EAST |
|         CHINA |        AFRICA |
|         CHINA |       AMERICA |
|         CHINA |          ASIA |
|         CHINA |        EUROPE |
|         CHINA |   MIDDLE EAST |
|       ROMANIA |        AFRICA |
|       ROMANIA |       AMERICA |
|       ROMANIA |          ASIA |
|       ROMANIA |        EUROPE |
|       ROMANIA |   MIDDLE EAST |
+---------------+---------------+

In [61]:
%%sql
SELECT
  o_orderpriority,
  COUNT(*) AS num_orders
FROM
  orders
GROUP BY
  o_orderpriority;

+-----------------+------------+
| o_orderpriority | num_orders |
+-----------------+------------+
|           5-LOW |      30244 |
|        3-MEDIUM |      29563 |
|        1-URGENT |      30111 |
| 4-NOT SPECIFIED |      29910 |
|          2-HIGH |      30172 |
+-----------------+------------+

In [62]:
%%sql
SELECT
  n.n_name AS nation_c_name,
  s.quantity AS supplied_items_quantity,
  c.quantity AS purchased_items_quantity
FROM
  nation n
  LEFT JOIN (
    SELECT
      n.n_nationkey,
      SUM(l.l_quantity) AS quantity
    FROM
      lineitem l
      JOIN supplier s ON l.l_suppkey = s.s_suppkey
      JOIN nation n ON s.s_nationkey = n.n_nationkey
    GROUP BY
      n.n_nationkey
  ) s ON n.n_nationkey = s.n_nationkey
  LEFT JOIN (
    SELECT
      n.n_nationkey,
      SUM(l.l_quantity) AS quantity
    FROM
      lineitem l
      JOIN orders o ON l.l_orderkey = o.o_orderkey
      JOIN customer c ON o.o_custkey = c.c_custkey
      JOIN nation n ON c.c_nationkey = n.n_nationkey
    GROUP BY
      n.n_nationkey
  ) c ON n.n_nationkey = c.n_nationkey;

+----------------+-------------------------+--------------------------+
|  nation_c_name | supplied_items_quantity | purchased_items_quantity |
+----------------+-------------------------+--------------------------+
|          JAPAN |               632809.00 |                594514.00 |
|         RUSSIA |               719815.00 |                607446.00 |
|      ARGENTINA |               583989.00 |                609330.00 |
|         JORDAN |               435841.00 |                609850.00 |
|         FRANCE |               534549.00 |                585564.00 |
|     MOZAMBIQUE |               523591.00 |                613443.00 |
|         CANADA |               569306.00 |                631774.00 |
|   SAUDI ARABIA |               720977.00 |                569819.00 |
|       ETHIOPIA |               506759.00 |                647056.00 |
|        ROMANIA |               506500.00 |                628528.00 |
|        MOROCCO |               624830.00 |                641135.00 |
|      INDONESIA |               686980.00 |                659643.00 |
|           PERU |               613397.00 |                568721.00 |
|          EGYPT |               610765.00 |                627841.00 |
|          INDIA |               719461.00 |                584063.00 |
| UNITED KINGDOM |               596263.00 |                606910.00 |
|        GERMANY |               765812.00 |                619356.00 |
|           IRAN |               609180.00 |                678349.00 |
|  UNITED STATES |               551367.00 |                603133.00 |
|        VIETNAM |               596045.00 |                607776.00 |
|           IRAQ |               654510.00 |                625030.00 |
|          KENYA |               545734.00 |                562545.00 |
|         BRAZIL |               664553.00 |                618707.00 |
|        ALGERIA |               558454.00 |                600846.00 |
|          CHINA |               803315.00 |                633423.00 |
+----------------+-------------------------+--------------------------+

In [63]:
%%sql
SELECT
    o_orderkey,
    o_totalprice,
    CASE
        WHEN o_totalprice > 100000 THEN 'high'
        WHEN o_totalprice BETWEEN 25000
        AND 100000 THEN 'medium'
        ELSE 'low'
    END AS order_price_bucket
FROM
    orders;

+------------+--------------+--------------------+
| o_orderkey | o_totalprice | order_price_bucket |
+------------+--------------+--------------------+
|          1 |    194029.55 |               high |
|          2 |     60951.63 |             medium |
|          3 |    247296.05 |               high |
|          4 |     53829.87 |             medium |
|          5 |    139660.54 |               high |
|          6 |     65843.52 |             medium |
|          7 |    231037.28 |               high |
|         32 |    166802.63 |               high |
|         33 |    118518.56 |               high |
|         34 |     75662.77 |             medium |
|         35 |    192885.43 |               high |
|         36 |     72196.43 |             medium |
|         37 |    156440.15 |               high |
|         38 |     64695.26 |             medium |
|         39 |    307811.89 |               high |
|         64 |     30616.90 |             medium |
|         65 |     99763.79 |             medium |
|         66 |    100991.26 |               high |
|         67 |    167270.36 |               high |
|         68 |    305815.83 |               high |
|         69 |    228015.94 |               high |
|         70 |    133507.10 |               high |
|         71 |    244449.86 |               high |
|         96 |     72504.36 |             medium |
|         97 |    128590.11 |               high |
|         98 |     62956.90 |             medium |
|         99 |    136624.34 |               high |
|        100 |    204408.59 |               high |
|        101 |    142434.13 |               high |
|        102 |    172239.95 |               high |
|        103 |    147675.81 |               high |
|        128 |     57495.50 |             medium |
|        129 |    273469.52 |               high |
|        130 |    169065.69 |               high |
|        131 |    143898.91 |               high |
|        132 |    180897.80 |               high |
|        133 |    120535.39 |               high |
|        134 |    203218.79 |               high |
|        135 |    280793.15 |               high |
|        160 |    114252.21 |               high |
|        161 |     22632.04 |                low |
|        162 |      3658.13 |                low |
|        163 |    172394.12 |               high |
|        164 |    315228.81 |               high |
|        165 |    204566.92 |               high |
|        166 |    152280.99 |               high |
|        167 |     53697.73 |             medium |
|        192 |    151014.95 |               high |
|        193 |     60599.97 |             medium |
|        194 |    169409.25 |               high |
|        195 |    169343.52 |               high |
|        196 |     55238.37 |             medium |
|        197 |    162567.01 |               high |
|        198 |    167234.32 |               high |
|        199 |     93001.13 |             medium |
|        224 |    232428.88 |               high |
|        225 |    229717.70 |               high |
|        226 |    255602.24 |               high |
|        227 |     59478.59 |             medium |
|        228 |      3803.63 |                low |
|        229 |    217643.52 |               high |
|        230 |    176248.58 |               high |
|        231 |    212400.50 |               high |
|        256 |    185998.58 |               high |
|        257 |     10429.67 |                low |
|        258 |    244576.64 |               high |
|        259 |    102311.15 |               high |
|        260 |    242001.54 |               high |
|        261 |    271008.54 |               high |
|        262 |    134127.81 |               high |
|        263 |     99162.08 |             medium |
|        288 |    234087.71 |               high |
|        289 |    218685.70 |               high |
|        290 |     90265.69 |             medium |
|        291 |     81679.04 |             medium |
|        292 |     51571.37 |             medium |
|        293 |     62804.27 |             medium |
|        294 |     58485.82 |             medium |
|        295 |    112253.57 |               high |
|        320 |     52957.12 |             medium |
|        321 |     59593.91 |             medium |
|        322 |    161012.25 |               high |
|        323 |     99307.09 |             medium |
|        324 |     45618.44 |             medium |
|        325 |    127006.18 |               high |
|        326 |    346777.54 |               high |
|        327 |     29089.13 |             medium |
|        352 |     21304.57 |                low |
|        353 |    278475.49 |               high |
|        354 |    223943.70 |               high |
|        355 |     98378.94 |             medium |
|        356 |    250722.11 |               high |
|        357 |    129581.13 |               high |
|        358 |    306323.97 |               high |
|        359 |    202575.81 |               high |
|        384 |    161989.84 |               high |
|        385 |     65722.70 |             medium |
|        386 |    101834.97 |               high |
|        387 |    188762.47 |               high |
|        388 |    173814.86 |               high |
+------------+--------------+--------------------+

# Chapter 2

In [64]:
%%sql
-- CTE definition
WITH
  supplier_nation_metrics AS ( -- CTE 1 defined using WITH keyword
    SELECT
      n.n_nationkey,
      SUM(l.l_QUANTITY) AS num_supplied_parts
    FROM
      lineitem l
      JOIN supplier s ON l.l_suppkey = s.s_suppkey
      JOIN nation n ON s.s_nationkey = n.n_nationkey
    GROUP BY
      n.n_nationkey
  ),
  buyer_nation_metrics AS ( -- CTE 2 defined just as a name
    SELECT
      n.n_nationkey,
      SUM(l.l_QUANTITY) AS num_purchased_parts
    FROM
      lineitem l
      JOIN orders o ON l.l_orderkey = o.o_orderkey
      JOIN customer c ON o.o_custkey = c.c_custkey
      JOIN nation n ON c.c_nationkey = n.n_nationkey
    GROUP BY
      n.n_nationkey
  )
SELECT -- The final select will not have a comma before it
  n.n_name AS nation_name,
  s.num_supplied_parts,
  b.num_purchased_parts
FROM
  nation n
  LEFT JOIN supplier_nation_metrics s ON n.n_nationkey = s.n_nationkey
  LEFT JOIN buyer_nation_metrics b ON n.n_nationkey = b.n_nationkey
LIMIT 10;

+-------------+--------------------+---------------------+
| nation_name | num_supplied_parts | num_purchased_parts |
+-------------+--------------------+---------------------+
|   ARGENTINA |          583989.00 |           609330.00 |
|      FRANCE |          534549.00 |           585564.00 |
|      CANADA |          569306.00 |           631774.00 |
|    ETHIOPIA |          506759.00 |           647056.00 |
|   INDONESIA |          686980.00 |           659643.00 |
|       EGYPT |          610765.00 |           627841.00 |
|       INDIA |          719461.00 |           584063.00 |
|     GERMANY |          765812.00 |           619356.00 |
|      BRAZIL |          664553.00 |           618707.00 |
|     ALGERIA |          558454.00 |           600846.00 |
+-------------+--------------------+---------------------+

In [65]:
%%sql
WITH lineitem_agg AS (
    SELECT 
        l_orderkey,
        SUM(l_extendedprice) AS total_price_without_discount
    FROM 
        lineitem
    GROUP BY 
        l_orderkey
)
SELECT 
    o.o_orderkey,
    o.o_totalprice, 
    l.total_price_without_discount - o.o_totalprice AS amount_lost_to_discount
FROM 
    orders o
JOIN 
    lineitem_agg l ON o.o_orderkey = l.l_orderkey
ORDER BY 
    o.o_orderkey;

+------------+--------------+-------------------------+
| o_orderkey | o_totalprice | amount_lost_to_discount |
+------------+--------------+-------------------------+
|          1 |    194029.55 |                 8951.76 |
|          2 |     60951.63 |                -2902.45 |
|          3 |    247296.05 |                15750.08 |
|          4 |     53829.87 |                -2445.87 |
|          5 |    139660.54 |                 3684.85 |
|          6 |     65843.52 |                 3641.00 |
|          7 |    231037.28 |                 7895.84 |
|         32 |    166802.63 |                  334.59 |
|         33 |    118518.56 |                 5797.76 |
|         34 |     75662.77 |                -1014.60 |
|         35 |    192885.43 |                 2396.99 |
|         36 |     72196.43 |                 7140.31 |
|         37 |    156440.15 |                 3513.85 |
|         38 |     64695.26 |                 1374.26 |
|         39 |    307811.89 |                 3782.16 |
|         64 |     30616.90 |                  979.49 |
|         65 |     99763.79 |                 -800.48 |
|         66 |    100991.26 |                -4942.51 |
|         67 |    167270.36 |                  453.77 |
|         68 |    305815.83 |                 -452.82 |
|         69 |    228015.94 |                 3306.58 |
|         70 |    133507.10 |                 2989.27 |
|         71 |    244449.86 |                -1193.24 |
|         96 |     72504.36 |                 -861.56 |
|         97 |    128590.11 |                -3641.11 |
|         98 |     62956.90 |                  461.31 |
|         99 |    136624.34 |                 4384.29 |
|        100 |    204408.59 |                 -117.17 |
|        101 |    142434.13 |                 8948.01 |
|        102 |    172239.95 |                 1096.66 |
|        103 |    147675.81 |                -6467.45 |
|        128 |     57495.50 |                 3064.34 |
|        129 |    273469.52 |                 4614.45 |
|        130 |    169065.69 |                 2791.52 |
|        131 |    143898.91 |                 4958.44 |
|        132 |    180897.80 |                -2783.90 |
|        133 |    120535.39 |                  479.18 |
|        134 |    203218.79 |                 4337.53 |
|        135 |    280793.15 |                -3759.73 |
|        160 |    114252.21 |                  432.57 |
|        161 |     22632.04 |                    2.28 |
|        162 |      3658.13 |                   37.71 |
|        163 |    172394.12 |                 -693.50 |
|        164 |    315228.81 |                10351.81 |
|        165 |    204566.92 |                  142.73 |
|        166 |    152280.99 |                 7723.32 |
|        167 |     53697.73 |                 4064.40 |
|        192 |    151014.95 |                  -21.92 |
|        193 |     60599.97 |                 -530.04 |
|        194 |    169409.25 |                 -458.82 |
|        195 |    169343.52 |                  946.26 |
|        196 |     55238.37 |                   36.83 |
|        197 |    162567.01 |                 3181.97 |
|        198 |    167234.32 |                 6354.20 |
|        199 |     93001.13 |                 2460.87 |
|        224 |    232428.88 |                 1773.77 |
|        225 |    229717.70 |                 2853.20 |
|        226 |    255602.24 |                14587.21 |
|        227 |     59478.59 |                  -36.68 |
|        228 |      3803.63 |                  109.57 |
|        229 |    217643.52 |                 3509.65 |
|        230 |    176248.58 |                 7827.05 |
|        231 |    212400.50 |                 8540.23 |
|        256 |    185998.58 |                 4318.01 |
|        257 |     10429.67 |                  333.67 |
|        258 |    244576.64 |                 9198.15 |
|        259 |    102311.15 |                 2216.30 |
|        260 |    242001.54 |                -3145.03 |
|        261 |    271008.54 |                -4561.08 |
|        262 |    134127.81 |                -1324.07 |
|        263 |     99162.08 |                 1897.05 |
|        288 |    234087.71 |                 4064.55 |
|        289 |    218685.70 |                -1892.64 |
|        290 |     90265.69 |                -1319.95 |
|        291 |     81679.04 |                 3966.48 |
|        292 |     51571.37 |                 2645.51 |
|        293 |     62804.27 |                  811.59 |
|        294 |     58485.82 |                 -579.06 |
|        295 |    112253.57 |                  -14.72 |
|        320 |     52957.12 |                 2073.81 |
|        321 |     59593.91 |                 -741.64 |
|        322 |    161012.25 |                -1068.28 |
|        323 |     99307.09 |                  969.52 |
|        324 |     45618.44 |                 2948.00 |
|        325 |    127006.18 |                 3546.74 |
|        326 |    346777.54 |                -2501.57 |
|        327 |     29089.13 |                  842.00 |
|        352 |     21304.57 |                  512.72 |
|        353 |    278475.49 |                -3660.60 |
|        354 |    223943.70 |                 3224.64 |
|        355 |     98378.94 |                 4166.75 |
|        356 |    250722.11 |                 3160.76 |
|        357 |    129581.13 |                 1043.17 |
|        358 |    306323.97 |                 6999.63 |
|        359 |    202575.81 |                -2995.23 |
|        384 |    161989.84 |                 4609.06 |
|        385 |     65722.70 |                  790.58 |
|        386 |    101834.97 |                 4889.35 |
|        387 |    188762.47 |                 9377.32 |
|        388 |    173814.86 |                 7131.12 |
+------------+--------------+-------------------------+

**Casestudy:**
  
Read the query below and answer the question

```sql
%%sql
with orders as (
select
        order_id,
        customer_id,
        order_status,
        order_purchase_timestamp::TIMESTAMP AS order_purchase_timestamp,
        order_approved_at::TIMESTAMP AS order_approved_at,
        order_delivered_carrier_date::TIMESTAMP AS order_delivered_carrier_date,
        order_delivered_customer_date::TIMESTAMP AS order_delivered_customer_date,
        order_estimated_delivery_date::TIMESTAMP AS order_estimated_delivery_date
    from raw_layer.orders
    ),
 stg_customers as (
    select
        customer_id,
        zipcode,
        city,
        state_code,
        datetime_created::TIMESTAMP as datetime_created,
        datetime_updated::TIMESTAMP as datetime_updated,
        dbt_valid_from,
        dbt_valid_to
    from customer_snapshot
),
state as (
select
        state_id::INT as state_id,
        state_code::VARCHAR(2) as state_code,
        state_name::VARCHAR(30) as state_name
    from raw_layer.state
    ),
dim_customers as (
select
    c.customer_id,
    c.zipcode,
    c.city,
    c.state_code,
    s.state_name,
    c.datetime_created,
    c.datetime_updated,
    c.dbt_valid_from::TIMESTAMP as valid_from,
    case
        when c.dbt_valid_to is NULL then '9999-12-31'::TIMESTAMP
        else c.dbt_valid_to::TIMESTAMP
    end as valid_to
from stg_customers as c
inner join state as s on c.state_code = s.state_code
)
select
    o.order_id,
    o.customer_id,
    o.order_status,
    o.order_purchase_timestamp,
    o.order_approved_at,
    o.order_delivered_carrier_date,
    o.order_delivered_customer_date,
    o.order_estimated_delivery_date,
    c.zipcode as customer_zipcode,
    c.city as customer_city,
    c.state_code as customer_state_code,
    c.state_name as customer_state_name
from orders as o
inner join dim_customers as c on
    o.customer_id = c.customer_id
    and o.order_purchase_timestamp >= c.valid_from
    and o.order_purchase_timestamp <= c.valid_to;
```

[Exercise]

**Time limit during live workshop: 10 min** 

**Scenario**: Assume you are building tables for your data team and creating this CTE.
    
**Question**: From a team-wide table reusability perspective, what do you think is wrong with the above query?

**Question**: How would you change this Code so that your colleagues can reuse your work?



The CTEs created cannot be reused by team members.

To reuse the CTEs the code will need to be duplicated across your code base, which is bad!

You can instead define the CTEs as tables or views that can be reused (e.g. dbt).

# Chapter 3

In [66]:
%%sql
SELECT
  o_custkey,
  o_orderdate,
  o_totalprice,
  SUM(o_totalprice) -- FUNCTION 
  OVER (
    PARTITION BY
      o_custkey -- PARTITION
    ORDER BY
      o_orderdate -- ORDER BY; ASCENDING ORDER unless specified as DESC
  ) AS running_sum
FROM
  orders
WHERE
  o_custkey = 4
ORDER BY
  o_orderdate
LIMIT
  10;

+-----------+-------------+--------------+-------------+
| o_custkey | o_orderdate | o_totalprice | running_sum |
+-----------+-------------+--------------+-------------+
|         4 |  1992-06-09 |    261208.46 |   261208.46 |
|         4 |  1992-07-16 |    206615.30 |   467823.76 |
|         4 |  1992-10-11 |    222977.75 |   690801.51 |
|         4 |  1993-08-13 |     80130.69 |   770932.20 |
|         4 |  1993-11-13 |     66417.98 |   837350.18 |
|         4 |  1994-03-02 |    274992.65 |  1112342.83 |
|         4 |  1994-04-29 |    199636.40 |  1311979.23 |
|         4 |  1995-05-13 |    107127.51 |  1419106.74 |
|         4 |  1995-08-28 |    282207.37 |  1701314.11 |
|         4 |  1995-09-18 |    181789.20 |  1883103.31 |
+-----------+-------------+--------------+-------------+

In [67]:
%%sql
SELECT
  o_custkey,
  o_orderdate,
  o_totalprice,
  AVG(o_totalprice) -- FUNCTION 
  OVER (
    PARTITION BY
      o_custkey -- PARTITION
    ORDER BY
      o_orderdate -- ORDER BY; ASCENDING ORDER unless specified as DESC
  ) AS running_sum
FROM
  orders
WHERE
  o_custkey = 4
ORDER BY
  o_orderdate
LIMIT
  10;

+-----------+-------------+--------------+---------------+
| o_custkey | o_orderdate | o_totalprice |   running_sum |
+-----------+-------------+--------------+---------------+
|         4 |  1992-06-09 |    261208.46 | 261208.460000 |
|         4 |  1992-07-16 |    206615.30 | 233911.880000 |
|         4 |  1992-10-11 |    222977.75 | 230267.170000 |
|         4 |  1993-08-13 |     80130.69 | 192733.050000 |
|         4 |  1993-11-13 |     66417.98 | 167470.036000 |
|         4 |  1994-03-02 |    274992.65 | 185390.471667 |
|         4 |  1994-04-29 |    199636.40 | 187425.604286 |
|         4 |  1995-05-13 |    107127.51 | 177388.342500 |
|         4 |  1995-08-28 |    282207.37 | 189034.901111 |
|         4 |  1995-09-18 |    181789.20 | 188310.331000 |
+-----------+-------------+--------------+---------------+

In [68]:
%%sql
SELECT
  *
FROM
  (
    SELECT
      o_orderdate,
      o_totalprice,
      o_custkey,
      RANK() -- RANKING FUNCTION 
      OVER (
        PARTITION BY
          o_orderdate -- PARTITION BY order date
        ORDER BY
          o_totalprice DESC -- ORDER rows withing partition by totalprice
      ) AS rnk
    FROM
      orders
  )
WHERE
  rnk <= 3
ORDER BY
  o_orderdate
LIMIT
  5;

+-------------+--------------+-----------+-----+
| o_orderdate | o_totalprice | o_custkey | rnk |
+-------------+--------------+-----------+-----+
|  1992-01-01 |    358534.43 |     10942 |   1 |
|  1992-01-01 |    307146.32 |      5426 |   2 |
|  1992-01-01 |    306169.25 |     12973 |   3 |
|  1992-01-02 |    319926.05 |     12161 |   1 |
|  1992-01-02 |    302943.34 |     10526 |   2 |
+-------------+--------------+-----------+-----+

In [69]:
%%sql 
SELECT
  *
FROM
  (
    SELECT
      o_orderdate,
      o_totalprice,
      o_custkey,
      RANK() -- RANKING FUNCTION 
      OVER (
        PARTITION BY
          o_orderdate -- PARTITION BY order date
        ORDER BY
          o_totalprice -- ORDER rows withing partition by totalprice
      ) AS rnk
    FROM
      orders
  )
WHERE
  rnk <= 3
ORDER BY
  o_orderdate
LIMIT
  5;

+-------------+--------------+-----------+-----+
| o_orderdate | o_totalprice | o_custkey | rnk |
+-------------+--------------+-----------+-----+
|  1992-01-01 |     12781.38 |      9376 |   1 |
|  1992-01-01 |     25496.77 |      9103 |   2 |
|  1992-01-01 |     30944.67 |     14218 |   3 |
|  1992-01-02 |     16908.46 |      2746 |   1 |
|  1992-01-02 |     25445.96 |      4355 |   2 |
+-------------+--------------+-----------+-----+

In [70]:
%%sql
-- Let's look at an example showing the difference between RANK, DENSE_RANK and ROW_NUMBER
SELECT 
    order_date,
    order_id,
    total_price,
    ROW_NUMBER() OVER (PARTITION BY order_date ORDER BY total_price) AS row_number,
    RANK() OVER (PARTITION BY order_date ORDER BY total_price) AS rank,
    DENSE_RANK() OVER (PARTITION BY order_date ORDER BY total_price) AS dense_rank
FROM (
    SELECT 
        '2024-07-08' AS order_date, 'order_1' AS order_id, 100 AS total_price UNION ALL
    SELECT 
        '2024-07-08', 'order_2', 200 UNION ALL
    SELECT 
        '2024-07-08', 'order_3', 150 UNION ALL
    SELECT 
        '2024-07-08', 'order_4', 90 UNION ALL
    SELECT 
        '2024-07-08', 'order_5', 100 UNION ALL
    SELECT 
        '2024-07-08', 'order_6', 90 UNION ALL
    SELECT 
        '2024-07-08', 'order_7', 100 UNION ALL
    SELECT 
        '2024-07-10', 'order_8', 100 UNION ALL
    SELECT 
        '2024-07-10', 'order_9', 100 UNION ALL
    SELECT 
        '2024-07-10', 'order_10', 100 UNION ALL
    SELECT 
        '2024-07-11', 'order_11', 100
) AS orders
ORDER BY order_date, row_number;

+------------+----------+-------------+------------+------+------------+
| order_date | order_id | total_price | row_number | rank | dense_rank |
+------------+----------+-------------+------------+------+------------+
| 2024-07-08 |  order_4 |          90 |          1 |    1 |          1 |
| 2024-07-08 |  order_6 |          90 |          2 |    1 |          1 |
| 2024-07-08 |  order_1 |         100 |          3 |    3 |          2 |
| 2024-07-08 |  order_5 |         100 |          4 |    3 |          2 |
| 2024-07-08 |  order_7 |         100 |          5 |    3 |          2 |
| 2024-07-08 |  order_3 |         150 |          6 |    6 |          3 |
| 2024-07-08 |  order_2 |         200 |          7 |    7 |          4 |
| 2024-07-10 |  order_8 |         100 |          1 |    1 |          1 |
| 2024-07-10 |  order_9 |         100 |          2 |    1 |          1 |
| 2024-07-10 | order_10 |         100 |          3 |    1 |          1 |
| 2024-07-11 | order_11 |         100 |          1 |    1 |          1 |
+------------+----------+-------------+------------+------+------------+

In [71]:
%%sql
SELECT
  o_orderdate,
  o_custkey,
  o_totalprice,
  o_totalprice - lag (o_totalprice) OVER (
    PARTITION BY
      o_custkey
    ORDER BY
      o_orderdate
  ) AS totalprice_diff
FROM
  orders
ORDER BY
  o_custkey,
  o_orderdate
LIMIT
  50;

+-------------+-----------+--------------+-----------------+
| o_orderdate | o_custkey | o_totalprice | totalprice_diff |
+-------------+-----------+--------------+-----------------+
|  1992-04-19 |         1 |     83779.26 |            None |
|  1992-04-26 |         1 |    283261.47 |       199482.21 |
|  1993-06-22 |         1 |    263247.54 |       -20013.93 |
|  1994-12-24 |         1 |     35523.05 |      -227724.49 |
|  1995-11-01 |         1 |    235155.22 |       199632.17 |
|  1996-05-08 |         1 |     81485.84 |      -153669.38 |
|  1996-12-09 |         1 |     45744.09 |       -35741.75 |
|  1996-12-26 |         1 |     11925.85 |       -33818.24 |
|  1997-03-04 |         1 |    268835.44 |       256909.59 |
|  1992-12-07 |         2 |    195693.26 |            None |
|  1993-10-28 |         2 |     96852.91 |       -98840.35 |
|  1994-05-08 |         2 |     36433.77 |       -60419.14 |
|  1995-04-09 |         2 |    209272.43 |       172838.66 |
|  1996-03-19 |         2 |    108967.23 |      -100305.20 |
|  1996-04-10 |         2 |     51599.57 |       -57367.66 |
|  1996-10-30 |         2 |    168931.80 |       117332.23 |
|  1996-11-20 |         2 |    233181.71 |        64249.91 |
|  1997-05-17 |         2 |    222236.47 |       -10945.24 |
|  1997-06-23 |         2 |    299326.40 |        77089.93 |
|  1998-05-22 |         2 |    122500.55 |      -176825.85 |
|  1992-06-09 |         4 |    261208.46 |            None |
|  1992-07-16 |         4 |    206615.30 |       -54593.16 |
|  1992-10-11 |         4 |    222977.75 |        16362.45 |
|  1993-08-13 |         4 |     80130.69 |      -142847.06 |
|  1993-11-13 |         4 |     66417.98 |       -13712.71 |
|  1994-03-02 |         4 |    274992.65 |       208574.67 |
|  1994-04-29 |         4 |    199636.40 |       -75356.25 |
|  1995-05-13 |         4 |    107127.51 |       -92508.89 |
|  1995-08-28 |         4 |    282207.37 |       175079.86 |
|  1995-09-18 |         4 |    181789.20 |      -100418.17 |
|  1995-10-29 |         4 |    162955.31 |       -18833.89 |
|  1996-03-03 |         4 |     33563.90 |      -129391.41 |
|  1996-08-13 |         4 |     44791.42 |        11227.52 |
|  1996-08-25 |         4 |    281282.72 |       236491.30 |
|  1996-09-22 |         4 |    280809.61 |         -473.11 |
|  1996-11-20 |         4 |    240814.11 |       -39995.50 |
|  1997-01-29 |         4 |    268534.86 |        27720.75 |
|  1997-03-09 |         4 |     15671.83 |      -252863.03 |
|  1998-03-19 |         4 |     71483.64 |        55811.81 |
|  1998-06-15 |         4 |     21012.53 |       -50471.11 |
|  1992-04-18 |         5 |    194064.63 |            None |
|  1992-05-03 |         5 |    138421.67 |       -55642.96 |
|  1994-06-19 |         5 |    146751.73 |         8330.06 |
|  1995-03-20 |         5 |     41715.84 |      -105035.89 |
|  1995-07-06 |         5 |    229069.00 |       187353.16 |
|  1995-10-09 |         5 |    164780.73 |       -64288.27 |
|  1997-01-05 |         5 |    175977.08 |        11196.35 |
|  1997-03-19 |         5 |    226251.50 |        50274.42 |
|  1997-10-05 |         5 |    117887.38 |      -108364.12 |
|  1998-06-26 |         5 |     64473.34 |       -53414.04 |
+-------------+-----------+--------------+-----------------+

In [72]:
%%sql
SELECT
  order_month,
  o_custkey,
  total_price,
  ROUND(
    AVG(total_price) OVER ( -- FUNCTION: RUNNING AVERAGE
      PARTITION BY
        o_custkey -- PARTITIONED BY customer
      ORDER BY
        order_month ROWS BETWEEN 1 PRECEDING
        AND 1 FOLLOWING -- WINDOW FRAME DEFINED AS 1 ROW PRECEDING to 1 ROW FOLLOWING
    ),
    2
  ) AS three_mo_total_price_avg
FROM
  (
    SELECT
      date_format(o_orderdate, 'yyyy-MM') AS order_month,
      o_custkey,
      SUM(o_totalprice) AS total_price
    FROM
      orders
    GROUP BY
      1,
      2
  )
LIMIT
  5;

+-------------+-----------+-------------+--------------------------+
| order_month | o_custkey | total_price | three_mo_total_price_avg |
+-------------+-----------+-------------+--------------------------+
|     1992-04 |         1 |   367040.73 |                315144.14 |
|     1993-06 |         1 |   263247.54 |                221937.11 |
|     1994-12 |         1 |    35523.05 |                177975.27 |
|     1995-11 |         1 |   235155.22 |                117388.04 |
|     1996-05 |         1 |    81485.84 |                124770.33 |
+-------------+-----------+-------------+--------------------------+

In [73]:
%%sql
SELECT
  order_month,
  o_custkey,
  total_price,
  ROUND(
    AVG(total_price) OVER (
      PARTITION BY
        o_custkey
      ORDER BY
        CAST(order_month AS DATE) RANGE BETWEEN INTERVAL '1' MONTH PRECEDING
        AND INTERVAL '1' MONTH FOLLOWING
    ),
    2
  ) AS consecutive_three_mo_total_price_avg,
  ROUND(
    AVG(total_price) OVER (
      PARTITION BY
        o_custkey
      ORDER BY
        order_month ROWS BETWEEN 1 PRECEDING
        AND 1 FOLLOWING
    ),
    2
  ) AS three_mo_total_price_avg
FROM
  (
    SELECT
    date_format(o_orderdate, 'yyyy-MM-01') AS order_month,
      o_custkey,
      SUM(o_totalprice) AS total_price
    FROM
      orders
    GROUP BY
      1,
      2
  )
ORDER BY
  o_custkey,
  order_month
LIMIT
  50;

+-------------+-----------+-------------+--------------------------------------+--------------------------+
| order_month | o_custkey | total_price | consecutive_three_mo_total_price_avg | three_mo_total_price_avg |
+-------------+-----------+-------------+--------------------------------------+--------------------------+
|  1992-04-01 |         1 |   367040.73 |                            367040.73 |                315144.14 |
|  1993-06-01 |         1 |   263247.54 |                            263247.54 |                221937.11 |
|  1994-12-01 |         1 |    35523.05 |                             35523.05 |                177975.27 |
|  1995-11-01 |         1 |   235155.22 |                            235155.22 |                117388.04 |
|  1996-05-01 |         1 |    81485.84 |                             81485.84 |                124770.33 |
|  1996-12-01 |         1 |    57669.94 |                             57669.94 |                135997.07 |
|  1997-03-01 |         1 |   268835.44 |                            268835.44 |                163252.69 |
|  1992-12-01 |         2 |   195693.26 |                            195693.26 |                146273.09 |
|  1993-10-01 |         2 |    96852.91 |                             96852.91 |                109659.98 |
|  1994-05-01 |         2 |    36433.77 |                             36433.77 |                114186.37 |
|  1995-04-01 |         2 |   209272.43 |                            209272.43 |                118224.48 |
|  1996-03-01 |         2 |   108967.23 |                             80283.40 |                123279.74 |
|  1996-04-01 |         2 |    51599.57 |                             80283.40 |                109832.87 |
|  1996-10-01 |         2 |   168931.80 |                            201056.76 |                151237.69 |
|  1996-11-01 |         2 |   233181.71 |                            201056.76 |                208116.66 |
|  1997-05-01 |         2 |   222236.47 |                            260781.44 |                251581.53 |
|  1997-06-01 |         2 |   299326.40 |                            260781.44 |                214687.81 |
|  1998-05-01 |         2 |   122500.55 |                            122500.55 |                210913.48 |
|  1992-06-01 |         4 |   261208.46 |                            233911.88 |                233911.88 |
|  1992-07-01 |         4 |   206615.30 |                            233911.88 |                230267.17 |
|  1992-10-01 |         4 |   222977.75 |                            222977.75 |                169907.91 |
|  1993-08-01 |         4 |    80130.69 |                             80130.69 |                123175.47 |
|  1993-11-01 |         4 |    66417.98 |                             66417.98 |                140513.77 |
|  1994-03-01 |         4 |   274992.65 |                            237314.53 |                180349.01 |
|  1994-04-01 |         4 |   199636.40 |                            237314.53 |                193918.85 |
|  1995-05-01 |         4 |   107127.51 |                            107127.51 |                196323.76 |
|  1995-08-01 |         4 |   282207.37 |                            231998.29 |                190374.69 |
|  1995-09-01 |         4 |   181789.20 |                            208983.96 |                208983.96 |
|  1995-10-01 |         4 |   162955.31 |                            172372.26 |                126102.80 |
|  1996-03-01 |         4 |    33563.90 |                             33563.90 |                174197.78 |
|  1996-08-01 |         4 |   326074.14 |                            303441.88 |                213482.55 |
|  1996-09-01 |         4 |   280809.61 |                            303441.88 |                282565.95 |
|  1996-11-01 |         4 |   240814.11 |                            240814.11 |                263386.19 |
|  1997-01-01 |         4 |   268534.86 |                            268534.86 |                175006.93 |
|  1997-03-01 |         4 |    15671.83 |                             15671.83 |                118563.44 |
|  1998-03-01 |         4 |    71483.64 |                             71483.64 |                 36056.00 |
|  1998-06-01 |         4 |    21012.53 |                             21012.53 |                 46248.09 |
|  1992-04-01 |         5 |   194064.63 |                            166243.15 |                166243.15 |
|  1992-05-01 |         5 |   138421.67 |                            166243.15 |                159746.01 |
|  1994-06-01 |         5 |   146751.73 |                            146751.73 |                108963.08 |
|  1995-03-01 |         5 |    41715.84 |                             41715.84 |                139178.86 |
|  1995-07-01 |         5 |   229069.00 |                            229069.00 |                145188.52 |
|  1995-10-01 |         5 |   164780.73 |                            164780.73 |                189942.27 |
|  1997-01-01 |         5 |   175977.08 |                            175977.08 |                189003.10 |
|  1997-03-01 |         5 |   226251.50 |                            226251.50 |                173371.99 |
|  1997-10-01 |         5 |   117887.38 |                            117887.38 |                136204.07 |
|  1998-06-01 |         5 |    64473.34 |                             64473.34 |                 91180.36 |
|  1992-05-01 |         7 |   143727.03 |                            143727.03 |                161333.72 |
|  1992-08-01 |         7 |   178940.40 |                            178940.40 |                163360.25 |
|  1993-06-01 |         7 |   167413.31 |                            167413.31 |                203574.02 |
+-------------+-----------+-------------+--------------------------------------+--------------------------+